require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

# The engine compiled here is engine/quickjs-rel: the committed, pre-patched
# projection of the engine/quickjs-ng submodule, generated by
# scripts/sync-quickjs-rel.js. The submodule cannot be what ships -- our patches
# live in its working tree, which `git submodule update` reverts, and npm does
# not pack submodules at all.
#
# One existence check remains, because a wrong `files` entry in package.json
# still produces a tarball without these sources, and a missing-source failure
# at `pod install` is far cheaper to read than the hundreds of compiler errors
# it becomes otherwise.
quickjs_dir = File.join(__dir__, "engine", "quickjs-rel")
unless File.exist?(File.join(quickjs_dir, "quickjs.c"))
  raise "[ReactNativeQuickJS] engine/quickjs-rel is missing. Run: node scripts/sync-quickjs-rel.js"
end

Pod::Spec.new do |s|
  s.name         = "ReactNativeQuickJS"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => min_ios_version_supported }
  s.source       = { :git => package["repository"]["url"], :tag => "v#{s.version}" }

  # engine/quickjs-rel contains only these files -- the sync script derives the
  # list from the #include closure and deletes anything else -- so the globs
  # cannot pick up a stray main() the way they could against the full submodule.
  s.source_files = [
    "apple/*.{h,mm}",
    "src/**/*.{h,cpp}",
    # The Chrome DevTools Protocol backend. quickjs-cdp.c needs only
    # <quickjs.h>; react/ needs jsinspector-modern and folly, which the
    # React-jsinspector dependency below provides.
    "modules/cdp/*.{h,c}",
    "modules/cdp/react/*.{h,cpp}",
    "engine/quickjs-rel/*.h",
    # libregexp.c #includes libregexp-backtrack.c.inc twice, to build the 8-bit
    # and 16-bit matchers, so the .inc has to be copied too.
    "engine/quickjs-rel/*.inc",
    "engine/quickjs-rel/quickjs.c",
    "engine/quickjs-rel/libregexp.c",
    "engine/quickjs-rel/libunicode.c",
    "engine/quickjs-rel/dtoa.c",
  ]

  # Consumers only ever need the C factory entry point.
  s.public_header_files = "apple/RCTQuickJSInstanceFactory.h"

  # DEFINES_MODULE makes CocoaPods emit a module map even though this builds as
  # a static library, which is what lets an app's AppDelegate.swift write
  # `import ReactNativeQuickJS`.
  s.module_name = "ReactNativeQuickJS"

  # Expo's ExpoModulesJSI is a prebuilt dynamic framework that resolves JSI from
  # the flat namespace when it loads. Two of the symbols it needs come from
  # React-jsi and nothing linked statically into the app refers to them, so the
  # linker drops both and dyld kills the app before main() with
  # "symbol not found in flat namespace '__ZTIN8facebook3jsi13MutableBufferE'".
  #
  # Both are named, not just the destructor: ld64 dead-strips per atom rather
  # than per object file, so keeping the destructor does not keep the typeinfo
  # sitting beside it in the same object.
  #
  # Plain React Native never loads JSI dynamically and does not need this; there
  # it retains two symbols nothing asks for.
  s.user_target_xcconfig = {
    "OTHER_LDFLAGS" => "$(inherited) " \
      "-Wl,-u,__ZN8facebook3jsi13MutableBufferD2Ev " \
      "-Wl,-u,__ZTIN8facebook3jsi13MutableBufferE"
  }

  s.pod_target_xcconfig = {
    "DEFINES_MODULE" => "YES",
    # Must be quickjs-rel and not quickjs-ng. Pointing this at the submodule
    # while compiling the -rel sources would take headers from one copy and
    # translation units from the other: fine while they agree, and a
    # struct-layout mismatch with no diagnostic the moment they do not.
    "HEADER_SEARCH_PATHS" =>
      "\"$(PODS_TARGET_SRCROOT)/src/bytecode\" " \
      "\"$(PODS_TARGET_SRCROOT)/src/module\" " \
      "\"$(PODS_TARGET_SRCROOT)/src/runtime\" " \
      "\"$(PODS_TARGET_SRCROOT)/engine/quickjs-rel\" " \
      "\"$(PODS_TARGET_SRCROOT)/modules/cdp\" " \
      "\"$(PODS_TARGET_SRCROOT)/modules/cdp/react\"",
    "GCC_C_LANGUAGE_STANDARD" => "gnu11",
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++20",
    # JS_ENABLE_DEBUGGER must agree with cmake/quickjs.cmake, which defaults it
    # on for the host and Android builds. quickjs.h declares the debugger entry
    # points either way, so a build that compiles them out fails at link rather
    # than at the call site.
    #
    # RNQJS_ENABLE_CDP is absent on purpose: undefined means no DevTools
    # backend, and react_native_quickjs_post_install defines it for debug only.
    "GCC_PREPROCESSOR_DEFINITIONS" =>
      "$(inherited) _GNU_SOURCE=1 JS_ENABLE_DEBUGGER=1",
    "USE_HEADERMAP" => "YES",
  }

  # quickjs builds warning-clean upstream, but not under React Native's flags.
  s.compiler_flags = "-Wno-unused-parameter -Wno-unused-variable -Wno-sign-compare -Wno-implicit-fallthrough"

  # The Hermes compatibility shim, opt-in.
  #
  # modules/hermes-compat publishes a source-compatible <hermes/hermes.h> whose
  # makeHermesRuntime() returns a QuickJS-backed runtime, so react-native-worklets
  # -- and so react-native-reanimated -- build and run unmodified.
  #
  # On by default: react-native-worklets does not build without it, and neither
  # does react-native-reanimated, which is most apps. RNQJS_HERMES_COMPAT=0 in
  # the Podfile turns it off.
  #
  # react_native_quickjs_post_install puts these headers on every pod's header
  # search path, so any library feature-detecting with
  # __has_include(<hermes/hermes.h>) believes this is a Hermes app -- which is
  # the point: what it then calls is this engine.
  hermes_compat = ENV["RNQJS_HERMES_COMPAT"] != "0"

  # The shim is source-compatible with Hermes, not ABI-compatible. With the
  # hermes-engine pod also installed the target has two <hermes/hermes.h> on one
  # search path and two definitions of makeHermesRuntime on one link line, and
  # pod ordering decides which wins. use_hermes() is what decides whether that
  # pod is there, so ask it rather than reading ENV["USE_HERMES"]: React Native
  # sets that pod up from use_hermes(), which never consults that variable.
  #
  # Skipped rather than raised. Now that the shim is on by default this is
  # reached by installing the package and running pod install before
  # `npx react-native-quickjs install` has edited the Podfile -- a normal step
  # in setting the package up, and no place to abort.
  if hermes_compat && defined?(use_hermes) && use_hermes()
    Pod::UI.warn(
      "[ReactNativeQuickJS] the Hermes compatibility shim was skipped because " \
      "the hermes-engine pod is installed. Add use_quickjs! to the Podfile " \
      "(`npx react-native-quickjs install` does it) and run pod install again."
    )
    hermes_compat = false
  end

  if hermes_compat
    s.subspec "HermesCompat" do |ss|
      ss.source_files = [
        "modules/hermes-compat/src/*.cpp",
        "modules/hermes-compat/include/**/*.h",
      ]

      # Private on purpose. This pod sets DEFINES_MODULE, so a public header
      # joins ReactNativeQuickJS-umbrella.h, which Clang compiles as Objective-C
      # while building the module -- and <hermes/hermes.h> reaches <cstdint>,
      # which that compile cannot resolve. CocoaPods would also install them
      # under Headers/Public/ReactNativeQuickJS/hermes/, so <hermes/hermes.h>
      # would not resolve for a consumer either.
      #
      # react_native_quickjs_post_install puts the source directory itself on
      # every pod's header search path instead, which is what worklets needs.
      ss.private_header_files = "modules/hermes-compat/include/**/*.h"

      ss.pod_target_xcconfig = {
        # Our own sources include <hermes/hermes.h> and
        # <hermes-compat/Diagnostics.h> from the source tree.
        "HEADER_SEARCH_PATHS" =>
          "$(inherited) \"$(PODS_TARGET_SRCROOT)/modules/hermes-compat/include\"",
        # Unconditional, not tied to the configuration: RNWorklets.podspec sets
        # HERMES_ENABLE_DEBUGGER=1 for every Debug build regardless of
        # USE_HERMES, so a Debug worklets references enableDebugging and needs
        # it defined. Safe only because no member declaration in the shim's
        # headers is conditional on this macro.
        "GCC_PREPROCESSOR_DEFINITIONS" => "$(inherited) HERMES_ENABLE_DEBUGGER=1",
      }
    end
  end

  install_modules_dependencies(s)

  s.dependency "React-jsi"
  s.dependency "React-cxxreact"
  s.dependency "React-RuntimeCore"
  add_dependency(s, "React-jsitooling", :framework_name => "JSITooling")
  add_dependency(s, "React-jsinspector", :framework_name => "jsinspector_modern")
end
