require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

# The engine compiled here is engine/quickjs-rel: the committed, pre-patched
# projection of the engine/quickjs-ng submodule, generated by
# scripts/sync-quickjs-rel.js. The submodule cannot be what ships -- our patches
# live in its working tree, which `git submodule update` reverts, and npm does
# not pack submodules at all.
#
# One existence check remains, because a wrong `files` entry in package.json
# still produces a tarball without these sources, and a missing-source failure
# at `pod install` is far cheaper to read than the hundreds of compiler errors
# it becomes otherwise.
quickjs_dir = File.join(__dir__, "engine", "quickjs-rel")
unless File.exist?(File.join(quickjs_dir, "quickjs.c"))
  raise "[ReactNativeQuickJS] engine/quickjs-rel is missing. Run: node scripts/sync-quickjs-rel.js"
end

Pod::Spec.new do |s|
  s.name         = "ReactNativeQuickJS"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => min_ios_version_supported }
  s.source       = { :git => package["repository"]["url"], :tag => "v#{s.version}" }

  # engine/quickjs-rel contains only these files -- the sync script derives the
  # list from the #include closure and deletes anything else -- so the globs
  # cannot pick up a stray main() the way they could against the full submodule.
  s.source_files = [
    "platform/apple/*.{h,mm}",
    "src/**/*.{h,cpp}",
    "engine/quickjs-rel/*.h",
    # libregexp.c #includes libregexp-backtrack.c.inc twice, to build the 8-bit
    # and 16-bit matchers, so the .inc has to be copied too.
    "engine/quickjs-rel/*.inc",
    "engine/quickjs-rel/quickjs.c",
    "engine/quickjs-rel/libregexp.c",
    "engine/quickjs-rel/libunicode.c",
    "engine/quickjs-rel/dtoa.c",
  ]

  # Consumers only ever need the C factory entry point.
  s.public_header_files = "platform/apple/RCTQuickJSInstanceFactory.h"

  # DEFINES_MODULE makes CocoaPods emit a module map even though this builds as
  # a static library, which is what lets an app's AppDelegate.swift write
  # `import ReactNativeQuickJS`.
  s.module_name = "ReactNativeQuickJS"

  s.pod_target_xcconfig = {
    "DEFINES_MODULE" => "YES",
    # Must be quickjs-rel and not quickjs-ng. Pointing this at the submodule
    # while compiling the -rel sources would take headers from one copy and
    # translation units from the other: fine while they agree, and a
    # struct-layout mismatch with no diagnostic the moment they do not.
    "HEADER_SEARCH_PATHS" =>
      "\"$(PODS_TARGET_SRCROOT)/src/bytecode\" " \
      "\"$(PODS_TARGET_SRCROOT)/src/module\" " \
      "\"$(PODS_TARGET_SRCROOT)/src/runtime\" " \
      "\"$(PODS_TARGET_SRCROOT)/engine/quickjs-rel\"",
    "GCC_C_LANGUAGE_STANDARD" => "gnu11",
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++20",
    # JS_ENABLE_DEBUGGER must agree with cmake/quickjs.cmake, which defaults it
    # on for the host and Android builds. quickjs.h declares the debugger entry
    # points either way, so a build that compiles them out fails at link rather
    # than at the call site.
    "GCC_PREPROCESSOR_DEFINITIONS" =>
      "$(inherited) _GNU_SOURCE=1 JS_ENABLE_DEBUGGER=1",
    "USE_HEADERMAP" => "YES",
  }

  # quickjs builds warning-clean upstream, but not under React Native's flags.
  s.compiler_flags = "-Wno-unused-parameter -Wno-unused-variable -Wno-sign-compare -Wno-implicit-fallthrough"

  install_modules_dependencies(s)

  s.dependency "React-jsi"
  s.dependency "React-cxxreact"
  s.dependency "React-RuntimeCore"
  add_dependency(s, "React-jsitooling", :framework_name => "JSITooling")
end
