require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

# The engine compiled here is engine/quickjs-rel: the committed, pre-patched
# projection of the engine/quickjs-ng submodule, generated by
# scripts/sync-quickjs-rel.js. The submodule cannot be what ships -- our patches
# live in its working tree, which `git submodule update` reverts, and npm does
# not pack submodules at all.
#
# One existence check remains, because a wrong `files` entry in package.json
# still produces a tarball without these sources, and a missing-source failure
# at `pod install` is far cheaper to read than the hundreds of compiler errors
# it becomes otherwise.
quickjs_dir = File.join(__dir__, "engine", "quickjs-rel")
unless File.exist?(File.join(quickjs_dir, "quickjs.c"))
  raise "[ReactNativeQuickJS] engine/quickjs-rel is missing. Run: node scripts/sync-quickjs-rel.js"
end

Pod::Spec.new do |s|
  s.name         = "ReactNativeQuickJS"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => min_ios_version_supported }
  s.source       = { :git => package["repository"]["url"], :tag => "v#{s.version}" }

  # engine/quickjs-rel contains only these files -- the sync script derives the
  # list from the #include closure and deletes anything else -- so the globs
  # cannot pick up a stray main() the way they could against the full submodule.
  s.source_files = [
    "apple/*.{h,mm}",
    "src/**/*.{h,cpp}",
    # The Chrome DevTools Protocol backend. quickjs-cdp.c needs only
    # <quickjs.h>; react/ needs jsinspector-modern and folly, which the
    # React-jsinspector dependency below provides.
    "modules/cdp/*.{h,c}",
    "modules/text-encoding/*.{h,cpp}",
    "modules/cdp/react/*.{h,cpp}",
    "engine/quickjs-rel/*.h",
    # libregexp.c #includes libregexp-backtrack.c.inc twice, to build the 8-bit
    # and 16-bit matchers, so the .inc has to be copied too.
    "engine/quickjs-rel/*.inc",
    "engine/quickjs-rel/quickjs.c",
    "engine/quickjs-rel/libregexp.c",
    "engine/quickjs-rel/libunicode.c",
    "engine/quickjs-rel/dtoa.c",
  ]

  # Consumers only ever need the C factory entry point.
  s.public_header_files = "apple/RCTQuickJSInstanceFactory.h"

  # DEFINES_MODULE makes CocoaPods emit a module map even though this builds as
  # a static library, which is what lets an app's AppDelegate.swift write
  # `import ReactNativeQuickJS`.
  s.module_name = "ReactNativeQuickJS"

  s.pod_target_xcconfig = {
    "DEFINES_MODULE" => "YES",
    # Must be quickjs-rel and not quickjs-ng. Pointing this at the submodule
    # while compiling the -rel sources would take headers from one copy and
    # translation units from the other: fine while they agree, and a
    # struct-layout mismatch with no diagnostic the moment they do not.
    "HEADER_SEARCH_PATHS" =>
      "\"$(PODS_TARGET_SRCROOT)/src/bytecode\" " \
      "\"$(PODS_TARGET_SRCROOT)/src/module\" " \
      "\"$(PODS_TARGET_SRCROOT)/src/runtime\" " \
      "\"$(PODS_TARGET_SRCROOT)/engine/quickjs-rel\" " \
      "\"$(PODS_TARGET_SRCROOT)/modules/text-encoding\" " \
      "\"$(PODS_TARGET_SRCROOT)/modules/cdp\" " \
      "\"$(PODS_TARGET_SRCROOT)/modules/cdp/react\"",
    "GCC_C_LANGUAGE_STANDARD" => "gnu11",
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++20",
    # JS_ENABLE_DEBUGGER must agree with cmake/quickjs.cmake, which defaults it
    # on for the host and Android builds. quickjs.h declares the debugger entry
    # points either way, so a build that compiles them out fails at link rather
    # than at the call site.
    #
    # RNQJS_ENABLE_CDP is absent on purpose: undefined means no DevTools
    # backend, and react_native_quickjs_post_install defines it for debug only.
    "GCC_PREPROCESSOR_DEFINITIONS" =>
      "$(inherited) _GNU_SOURCE=1 JS_ENABLE_DEBUGGER=1",
    "USE_HEADERMAP" => "YES",
  }

  # quickjs builds warning-clean upstream, but not under React Native's flags.
  s.compiler_flags = "-Wno-unused-parameter -Wno-unused-variable -Wno-sign-compare -Wno-implicit-fallthrough"

  # The Hermes compatibility shim, opt-in.
  #
  # modules/hermes-compat publishes a source-compatible <hermes/hermes.h> whose
  # makeHermesRuntime() returns a QuickJS-backed runtime, so react-native-worklets
  # -- and so react-native-reanimated -- build and run unmodified.
  #
  # Opt-in because these headers land in $(PODS_ROOT)/Headers/Public/hermes/,
  # which CocoaPods puts on every pod's header search path. From that moment any
  # library feature-detecting with __has_include(<hermes/hermes.h>) believes this
  # is a Hermes app. That is an app-wide behavioural change and should be a
  # decision, not a side effect of installing a pod. Turn it on in the Podfile,
  # before use_native_modules!:
  #
  #   ENV["RNQJS_HERMES_COMPAT"] = "1"
  if ENV["RNQJS_HERMES_COMPAT"] == "1"
    # The shim is source-compatible with Hermes, not ABI-compatible. With the
    # hermes-engine pod also installed the target has two <hermes/hermes.h> on
    # one search path and two definitions of makeHermesRuntime on one link line,
    # and pod ordering decides which wins. use_hermes() is what decides whether
    # that pod is there, so ask it rather than reading ENV["USE_HERMES"], which
    # on React Native 0.85 aborts pod install and does not control this.
    if defined?(use_hermes) && use_hermes()
      raise <<~MSG
        [ReactNativeQuickJS] RNQJS_HERMES_COMPAT=1 cannot be used while the
        hermes-engine pod is installed. The shim replaces Hermes rather than
        extending it: installing both puts two <hermes/hermes.h> on one header
        search path and two definitions of facebook::hermes::makeHermesRuntime
        on one link line.
      MSG
    end

    s.subspec "HermesCompat" do |ss|
      ss.source_files = [
        "modules/hermes-compat/src/*.cpp",
        "modules/hermes-compat/include/hermes/**/*.h",
      ]

      # header_dir and header_mappings_dir are what land these at
      # Headers/Public/hermes/hermes.h and
      # Headers/Public/hermes/inspector-modern/chrome/Registration.h -- the exact
      # paths worklets includes. Without the mapping CocoaPods flattens the tree
      # and the nested includes are not found.
      ss.public_header_files = "modules/hermes-compat/include/hermes/**/*.h"
      ss.header_dir = "hermes"
      ss.header_mappings_dir = "modules/hermes-compat/include/hermes"

      ss.pod_target_xcconfig = {
        # Our own sources include <hermes/hermes.h> and
        # <hermes-compat/Diagnostics.h> from the source tree, not the published
        # copy. An embedder installing a diagnostics handler adds this too.
        "HEADER_SEARCH_PATHS" =>
          "$(inherited) \"$(PODS_TARGET_SRCROOT)/modules/hermes-compat/include\"",
        # Unconditional, not tied to the configuration: RNWorklets.podspec sets
        # HERMES_ENABLE_DEBUGGER=1 for every Debug build regardless of
        # USE_HERMES, so a Debug worklets references enableDebugging and needs
        # it defined. Safe only because no member declaration in the shim's
        # headers is conditional on this macro.
        "GCC_PREPROCESSOR_DEFINITIONS" => "$(inherited) HERMES_ENABLE_DEBUGGER=1",
      }
    end
  end

  install_modules_dependencies(s)

  s.dependency "React-jsi"
  s.dependency "React-cxxreact"
  s.dependency "React-RuntimeCore"
  add_dependency(s, "React-jsitooling", :framework_name => "JSITooling")
  add_dependency(s, "React-jsinspector", :framework_name => "jsinspector_modern")
end
