/*
 * GENERATED by modules/intl/scripts/gen-plural-data.js. DO NOT EDIT.
 *
 * Source: make-plural 8.1.0
 *         (Unicode-DFS-2016 licence), which compiles the CLDR plural rules.
 *
 * This is the only per-locale table in modules/intl, and it is here because
 * Apple has no plural-category API in Objective-C or in Swift while Android
 * does — see modules/intl/scripts/gen-plural-data.js for the full argument,
 * and docs/intl-completeness-map.md for the measurement behind it.
 *
 * Selectors take the number as a decimal STRING, which is how the ECMA-402
 * operands v/w/f/t (visible fraction digits) can be correct: js/intl.js passes
 * the same rounded string it hands to the platform for formatting.
 */

/* cardinal: 224 locales */
var PLURAL_CARDINAL = (function () {
const a = (n) => n == 1 ? 'one' : 'other';
const b = (n) => (n == 0 || n == 1) ? 'one' : 'other';
const c = (n) => n >= 0 && n <= 1 ? 'one' : 'other';
const d = (n) => {
  const s = String(n).split('.'), v0 = !s[1];
  return n == 1 && v0 ? 'one' : 'other';
};
const e = (n) => 'other';
const f = (n, c) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1], i1000000 = i.slice(-6);
  return n == 1 && v0 ? 'one'
    : !c && i != 0 && i1000000 == 0 && v0 || c > 5 ? 'many'
    : 'other';
};
const g = (n) => n == 1 ? 'one'
    : n == 2 ? 'two'
    : 'other';
  return {
    "af": a,
    "ak": b,
    "am": c,
    "an": a,
    "ar": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n100 = t0 && s[0].slice(-2);
  return n == 0 ? 'zero'
    : n == 1 ? 'one'
    : n == 2 ? 'two'
    : (n100 >= 3 && n100 <= 10) ? 'few'
    : (n100 >= 11 && n100 <= 99) ? 'many'
    : 'other';
},
    "ars": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n100 = t0 && s[0].slice(-2);
  return n == 0 ? 'zero'
    : n == 1 ? 'one'
    : n == 2 ? 'two'
    : (n100 >= 3 && n100 <= 10) ? 'few'
    : (n100 >= 11 && n100 <= 99) ? 'many'
    : 'other';
},
    "as": c,
    "asa": a,
    "ast": d,
    "az": a,
    "bal": a,
    "be": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
  return n10 == 1 && n100 != 11 ? 'one'
    : (n10 >= 2 && n10 <= 4) && (n100 < 12 || n100 > 14) ? 'few'
    : t0 && n10 == 0 || (n10 >= 5 && n10 <= 9) || (n100 >= 11 && n100 <= 14) ? 'many'
    : 'other';
},
    "bem": a,
    "bez": a,
    "bg": a,
    "bho": b,
    "blo": (n) => n == 0 ? 'zero'
    : n == 1 ? 'one'
    : 'other',
    "bm": e,
    "bn": c,
    "bo": e,
    "br": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2), n1000000 = t0 && s[0].slice(-6);
  return n10 == 1 && n100 != 11 && n100 != 71 && n100 != 91 ? 'one'
    : n10 == 2 && n100 != 12 && n100 != 72 && n100 != 92 ? 'two'
    : ((n10 == 3 || n10 == 4) || n10 == 9) && (n100 < 10 || n100 > 19) && (n100 < 70 || n100 > 79) && (n100 < 90 || n100 > 99) ? 'few'
    : n != 0 && t0 && n1000000 == 0 ? 'many'
    : 'other';
},
    "brx": a,
    "bs": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1], i10 = i.slice(-1), i100 = i.slice(-2), f10 = f.slice(-1), f100 = f.slice(-2);
  return v0 && i10 == 1 && i100 != 11 || f10 == 1 && f100 != 11 ? 'one'
    : v0 && (i10 >= 2 && i10 <= 4) && (i100 < 12 || i100 > 14) || (f10 >= 2 && f10 <= 4) && (f100 < 12 || f100 > 14) ? 'few'
    : 'other';
},
    "ca": f,
    "ce": a,
    "ceb": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1], i10 = i.slice(-1), f10 = f.slice(-1);
  return v0 && (i == 1 || i == 2 || i == 3) || v0 && i10 != 4 && i10 != 6 && i10 != 9 || !v0 && f10 != 4 && f10 != 6 && f10 != 9 ? 'one' : 'other';
},
    "cgg": a,
    "chr": a,
    "ckb": a,
    "cs": (n) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1];
  return n == 1 && v0 ? 'one'
    : (i >= 2 && i <= 4) && v0 ? 'few'
    : !v0 ? 'many'
    : 'other';
},
    "csw": b,
    "cv": (n) => n == 0 ? 'zero'
    : n == 1 ? 'one'
    : 'other',
    "cy": (n) => n == 0 ? 'zero'
    : n == 1 ? 'one'
    : n == 2 ? 'two'
    : n == 3 ? 'few'
    : n == 6 ? 'many'
    : 'other',
    "da": (n) => {
  const s = String(n).split('.'), i = s[0], t0 = Number(s[0]) == n;
  return n == 1 || !t0 && (i == 0 || i == 1) ? 'one' : 'other';
},
    "de": d,
    "doi": c,
    "dsb": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1], i100 = i.slice(-2), f100 = f.slice(-2);
  return v0 && i100 == 1 || f100 == 1 ? 'one'
    : v0 && i100 == 2 || f100 == 2 ? 'two'
    : v0 && (i100 == 3 || i100 == 4) || (f100 == 3 || f100 == 4) ? 'few'
    : 'other';
},
    "dv": a,
    "dz": e,
    "ee": a,
    "el": a,
    "en": d,
    "eo": a,
    "es": (n, c) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1], i1000000 = i.slice(-6);
  return n == 1 ? 'one'
    : !c && i != 0 && i1000000 == 0 && v0 || c > 5 ? 'many'
    : 'other';
},
    "et": d,
    "eu": a,
    "fa": c,
    "ff": (n) => n >= 0 && n < 2 ? 'one' : 'other',
    "fi": d,
    "fil": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1], i10 = i.slice(-1), f10 = f.slice(-1);
  return v0 && (i == 1 || i == 2 || i == 3) || v0 && i10 != 4 && i10 != 6 && i10 != 9 || !v0 && f10 != 4 && f10 != 6 && f10 != 9 ? 'one' : 'other';
},
    "fo": a,
    "fr": (n, c) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1], i1000000 = i.slice(-6);
  return n >= 0 && n < 2 ? 'one'
    : !c && i != 0 && i1000000 == 0 && v0 || c > 5 ? 'many'
    : 'other';
},
    "fur": a,
    "fy": d,
    "ga": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n;
  return n == 1 ? 'one'
    : n == 2 ? 'two'
    : (t0 && n >= 3 && n <= 6) ? 'few'
    : (t0 && n >= 7 && n <= 10) ? 'many'
    : 'other';
},
    "gd": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n;
  return (n == 1 || n == 11) ? 'one'
    : (n == 2 || n == 12) ? 'two'
    : ((t0 && n >= 3 && n <= 10) || (t0 && n >= 13 && n <= 19)) ? 'few'
    : 'other';
},
    "gl": d,
    "gsw": a,
    "gu": c,
    "guw": b,
    "gv": (n) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1], i10 = i.slice(-1), i100 = i.slice(-2);
  return v0 && i10 == 1 ? 'one'
    : v0 && i10 == 2 ? 'two'
    : v0 && (i100 == 0 || i100 == 20 || i100 == 40 || i100 == 60 || i100 == 80) ? 'few'
    : !v0 ? 'many'
    : 'other';
},
    "ha": a,
    "haw": a,
    "he": (n) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1];
  return i == 1 && v0 || i == 0 && !v0 ? 'one'
    : i == 2 && v0 ? 'two'
    : 'other';
},
    "hi": c,
    "hnj": e,
    "hr": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1], i10 = i.slice(-1), i100 = i.slice(-2), f10 = f.slice(-1), f100 = f.slice(-2);
  return v0 && i10 == 1 && i100 != 11 || f10 == 1 && f100 != 11 ? 'one'
    : v0 && (i10 >= 2 && i10 <= 4) && (i100 < 12 || i100 > 14) || (f10 >= 2 && f10 <= 4) && (f100 < 12 || f100 > 14) ? 'few'
    : 'other';
},
    "hsb": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1], i100 = i.slice(-2), f100 = f.slice(-2);
  return v0 && i100 == 1 || f100 == 1 ? 'one'
    : v0 && i100 == 2 || f100 == 2 ? 'two'
    : v0 && (i100 == 3 || i100 == 4) || (f100 == 3 || f100 == 4) ? 'few'
    : 'other';
},
    "hu": a,
    "hy": (n) => n >= 0 && n < 2 ? 'one' : 'other',
    "ia": d,
    "id": e,
    "ie": d,
    "ig": e,
    "ii": e,
    "io": d,
    "is": (n) => {
  const s = String(n).split('.'), i = s[0], t = (s[1] || '').replace(/0+$/, ''), t0 = Number(s[0]) == n, i10 = i.slice(-1), i100 = i.slice(-2);
  return t0 && i10 == 1 && i100 != 11 || t % 10 == 1 && t % 100 != 11 ? 'one' : 'other';
},
    "it": f,
    "iu": g,
    "ja": e,
    "jbo": e,
    "jgo": a,
    "jmc": a,
    "jv": e,
    "jw": e,
    "ka": a,
    "kab": (n) => n >= 0 && n < 2 ? 'one' : 'other',
    "kaj": a,
    "kcg": a,
    "kde": e,
    "kea": e,
    "kk": a,
    "kkj": a,
    "kl": a,
    "km": e,
    "kn": c,
    "ko": e,
    "kok": c,
    "kok_Latn": c,
    "ks": a,
    "ksb": a,
    "ksh": (n) => n == 0 ? 'zero'
    : n == 1 ? 'one'
    : 'other',
    "ku": a,
    "kw": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n100 = t0 && s[0].slice(-2), n1000 = t0 && s[0].slice(-3), n100000 = t0 && s[0].slice(-5), n1000000 = t0 && s[0].slice(-6);
  return n == 0 ? 'zero'
    : n == 1 ? 'one'
    : (n100 == 2 || n100 == 22 || n100 == 42 || n100 == 62 || n100 == 82) || t0 && n1000 == 0 && ((n100000 >= 1000 && n100000 <= 20000) || n100000 == 40000 || n100000 == 60000 || n100000 == 80000) || n != 0 && n1000000 == 100000 ? 'two'
    : (n100 == 3 || n100 == 23 || n100 == 43 || n100 == 63 || n100 == 83) ? 'few'
    : n != 1 && (n100 == 1 || n100 == 21 || n100 == 41 || n100 == 61 || n100 == 81) ? 'many'
    : 'other';
},
    "ky": a,
    "lag": (n) => {
  const s = String(n).split('.'), i = s[0];
  return n == 0 ? 'zero'
    : (i == 0 || i == 1) && n != 0 ? 'one'
    : 'other';
},
    "lb": a,
    "lg": a,
    "lij": d,
    "lkt": e,
    "lld": f,
    "ln": b,
    "lo": e,
    "lt": (n) => {
  const s = String(n).split('.'), f = s[1] || '', t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
  return n10 == 1 && (n100 < 11 || n100 > 19) ? 'one'
    : (n10 >= 2 && n10 <= 9) && (n100 < 11 || n100 > 19) ? 'few'
    : f != 0 ? 'many'
    : 'other';
},
    "lv": (n) => {
  const s = String(n).split('.'), f = s[1] || '', v = f.length, t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2), f100 = f.slice(-2), f10 = f.slice(-1);
  return t0 && n10 == 0 || (n100 >= 11 && n100 <= 19) || v == 2 && (f100 >= 11 && f100 <= 19) ? 'zero'
    : n10 == 1 && n100 != 11 || v == 2 && f10 == 1 && f100 != 11 || v != 2 && f10 == 1 ? 'one'
    : 'other';
},
    "mas": a,
    "mg": b,
    "mgo": a,
    "mk": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1], i10 = i.slice(-1), i100 = i.slice(-2), f10 = f.slice(-1), f100 = f.slice(-2);
  return v0 && i10 == 1 && i100 != 11 || f10 == 1 && f100 != 11 ? 'one' : 'other';
},
    "ml": a,
    "mn": a,
    "mo": (n) => {
  const s = String(n).split('.'), v0 = !s[1], t0 = Number(s[0]) == n, n100 = t0 && s[0].slice(-2);
  return n == 1 && v0 ? 'one'
    : !v0 || n == 0 || n != 1 && (n100 >= 1 && n100 <= 19) ? 'few'
    : 'other';
},
    "mr": a,
    "ms": e,
    "mt": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n100 = t0 && s[0].slice(-2);
  return n == 1 ? 'one'
    : n == 2 ? 'two'
    : n == 0 || (n100 >= 3 && n100 <= 10) ? 'few'
    : (n100 >= 11 && n100 <= 19) ? 'many'
    : 'other';
},
    "my": e,
    "nah": a,
    "naq": g,
    "nb": a,
    "nd": a,
    "ne": a,
    "nl": d,
    "nn": a,
    "nnh": a,
    "no": a,
    "nqo": e,
    "nr": a,
    "nso": b,
    "ny": a,
    "nyn": a,
    "om": a,
    "or": a,
    "os": a,
    "osa": e,
    "pa": b,
    "pap": a,
    "pcm": c,
    "pl": (n) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1], i10 = i.slice(-1), i100 = i.slice(-2);
  return n == 1 && v0 ? 'one'
    : v0 && (i10 >= 2 && i10 <= 4) && (i100 < 12 || i100 > 14) ? 'few'
    : v0 && i != 1 && (i10 == 0 || i10 == 1) || v0 && (i10 >= 5 && i10 <= 9) || v0 && (i100 >= 12 && i100 <= 14) ? 'many'
    : 'other';
},
    "prg": (n) => {
  const s = String(n).split('.'), f = s[1] || '', v = f.length, t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2), f100 = f.slice(-2), f10 = f.slice(-1);
  return t0 && n10 == 0 || (n100 >= 11 && n100 <= 19) || v == 2 && (f100 >= 11 && f100 <= 19) ? 'zero'
    : n10 == 1 && n100 != 11 || v == 2 && f10 == 1 && f100 != 11 || v != 2 && f10 == 1 ? 'one'
    : 'other';
},
    "ps": a,
    "pt": (n, c) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1], i1000000 = i.slice(-6);
  return (i == 0 || i == 1) ? 'one'
    : !c && i != 0 && i1000000 == 0 && v0 || c > 5 ? 'many'
    : 'other';
},
    "pt_PT": f,
    "rm": a,
    "ro": (n) => {
  const s = String(n).split('.'), v0 = !s[1], t0 = Number(s[0]) == n, n100 = t0 && s[0].slice(-2);
  return n == 1 && v0 ? 'one'
    : !v0 || n == 0 || n != 1 && (n100 >= 1 && n100 <= 19) ? 'few'
    : 'other';
},
    "rof": a,
    "ru": (n) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1], i10 = i.slice(-1), i100 = i.slice(-2);
  return v0 && i10 == 1 && i100 != 11 ? 'one'
    : v0 && (i10 >= 2 && i10 <= 4) && (i100 < 12 || i100 > 14) ? 'few'
    : v0 && i10 == 0 || v0 && (i10 >= 5 && i10 <= 9) || v0 && (i100 >= 11 && i100 <= 14) ? 'many'
    : 'other';
},
    "rwk": a,
    "sah": e,
    "saq": a,
    "sat": g,
    "sc": d,
    "scn": f,
    "sd": a,
    "sdh": a,
    "se": g,
    "seh": a,
    "ses": e,
    "sg": e,
    "sgs": (n) => {
  const s = String(n).split('.'), f = s[1] || '', t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
  return n10 == 1 && n100 != 11 ? 'one'
    : n == 2 ? 'two'
    : n != 2 && (n10 >= 2 && n10 <= 9) && (n100 < 11 || n100 > 19) ? 'few'
    : f != 0 ? 'many'
    : 'other';
},
    "sh": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1], i10 = i.slice(-1), i100 = i.slice(-2), f10 = f.slice(-1), f100 = f.slice(-2);
  return v0 && i10 == 1 && i100 != 11 || f10 == 1 && f100 != 11 ? 'one'
    : v0 && (i10 >= 2 && i10 <= 4) && (i100 < 12 || i100 > 14) || (f10 >= 2 && f10 <= 4) && (f100 < 12 || f100 > 14) ? 'few'
    : 'other';
},
    "shi": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n;
  return n >= 0 && n <= 1 ? 'one'
    : (t0 && n >= 2 && n <= 10) ? 'few'
    : 'other';
},
    "si": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '';
  return (n == 0 || n == 1) || i == 0 && f == 1 ? 'one' : 'other';
},
    "sk": (n) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1];
  return n == 1 && v0 ? 'one'
    : (i >= 2 && i <= 4) && v0 ? 'few'
    : !v0 ? 'many'
    : 'other';
},
    "sl": (n) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1], i100 = i.slice(-2);
  return v0 && i100 == 1 ? 'one'
    : v0 && i100 == 2 ? 'two'
    : v0 && (i100 == 3 || i100 == 4) || !v0 ? 'few'
    : 'other';
},
    "sma": g,
    "smi": g,
    "smj": g,
    "smn": g,
    "sms": g,
    "sn": a,
    "so": a,
    "sq": a,
    "sr": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1], i10 = i.slice(-1), i100 = i.slice(-2), f10 = f.slice(-1), f100 = f.slice(-2);
  return v0 && i10 == 1 && i100 != 11 || f10 == 1 && f100 != 11 ? 'one'
    : v0 && (i10 >= 2 && i10 <= 4) && (i100 < 12 || i100 > 14) || (f10 >= 2 && f10 <= 4) && (f100 < 12 || f100 > 14) ? 'few'
    : 'other';
},
    "ss": a,
    "ssy": a,
    "st": a,
    "su": e,
    "sv": d,
    "sw": d,
    "syr": a,
    "ta": a,
    "te": a,
    "teo": a,
    "th": e,
    "ti": b,
    "tig": a,
    "tk": a,
    "tl": (n) => {
  const s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1], i10 = i.slice(-1), f10 = f.slice(-1);
  return v0 && (i == 1 || i == 2 || i == 3) || v0 && i10 != 4 && i10 != 6 && i10 != 9 || !v0 && f10 != 4 && f10 != 6 && f10 != 9 ? 'one' : 'other';
},
    "tn": a,
    "to": e,
    "tpi": e,
    "tr": a,
    "ts": a,
    "tzm": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n;
  return (n == 0 || n == 1) || (t0 && n >= 11 && n <= 99) ? 'one' : 'other';
},
    "ug": a,
    "uk": (n) => {
  const s = String(n).split('.'), i = s[0], v0 = !s[1], i10 = i.slice(-1), i100 = i.slice(-2);
  return v0 && i10 == 1 && i100 != 11 ? 'one'
    : v0 && (i10 >= 2 && i10 <= 4) && (i100 < 12 || i100 > 14) ? 'few'
    : v0 && i10 == 0 || v0 && (i10 >= 5 && i10 <= 9) || v0 && (i100 >= 11 && i100 <= 14) ? 'many'
    : 'other';
},
    "und": e,
    "ur": d,
    "uz": a,
    "ve": a,
    "vec": f,
    "vi": e,
    "vo": a,
    "vun": a,
    "wa": b,
    "wae": a,
    "wo": e,
    "xh": a,
    "xog": a,
    "yi": d,
    "yo": e,
    "yue": e,
    "zh": e,
    "zu": c
  };
})();

/* ordinal: 108 locales */
var PLURAL_ORDINAL = (function () {
const a = (n) => 'other';
const b = (n) => n == 1 ? 'one' : 'other';
  return {
    "af": a,
    "am": a,
    "an": a,
    "ar": a,
    "as": (n) => (n == 1 || n == 5 || n == 7 || n == 8 || n == 9 || n == 10) ? 'one'
    : (n == 2 || n == 3) ? 'two'
    : n == 4 ? 'few'
    : n == 6 ? 'many'
    : 'other',
    "ast": a,
    "az": (n) => {
  const s = String(n).split('.'), i = s[0], i10 = i.slice(-1), i100 = i.slice(-2), i1000 = i.slice(-3);
  return (i10 == 1 || i10 == 2 || i10 == 5 || i10 == 7 || i10 == 8) || (i100 == 20 || i100 == 50 || i100 == 70 || i100 == 80) ? 'one'
    : (i10 == 3 || i10 == 4) || (i1000 == 100 || i1000 == 200 || i1000 == 300 || i1000 == 400 || i1000 == 500 || i1000 == 600 || i1000 == 700 || i1000 == 800 || i1000 == 900) ? 'few'
    : i == 0 || i10 == 6 || (i100 == 40 || i100 == 60 || i100 == 90) ? 'many'
    : 'other';
},
    "bal": b,
    "be": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
  return (n10 == 2 || n10 == 3) && n100 != 12 && n100 != 13 ? 'few' : 'other';
},
    "bg": a,
    "blo": (n) => {
  const s = String(n).split('.'), i = s[0];
  return i == 0 ? 'zero'
    : i == 1 ? 'one'
    : (i == 2 || i == 3 || i == 4 || i == 5 || i == 6) ? 'few'
    : 'other';
},
    "bn": (n) => (n == 1 || n == 5 || n == 7 || n == 8 || n == 9 || n == 10) ? 'one'
    : (n == 2 || n == 3) ? 'two'
    : n == 4 ? 'few'
    : n == 6 ? 'many'
    : 'other',
    "bs": a,
    "ca": (n) => (n == 1 || n == 3) ? 'one'
    : n == 2 ? 'two'
    : n == 4 ? 'few'
    : 'other',
    "ce": a,
    "cs": a,
    "cv": a,
    "cy": (n) => (n == 0 || n == 7 || n == 8 || n == 9) ? 'zero'
    : n == 1 ? 'one'
    : n == 2 ? 'two'
    : (n == 3 || n == 4) ? 'few'
    : (n == 5 || n == 6) ? 'many'
    : 'other',
    "da": a,
    "de": a,
    "dsb": a,
    "el": a,
    "en": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
  return n10 == 1 && n100 != 11 ? 'one'
    : n10 == 2 && n100 != 12 ? 'two'
    : n10 == 3 && n100 != 13 ? 'few'
    : 'other';
},
    "es": a,
    "et": a,
    "eu": a,
    "fa": a,
    "fi": a,
    "fil": b,
    "fr": b,
    "fy": a,
    "ga": b,
    "gd": (n) => (n == 1 || n == 11) ? 'one'
    : (n == 2 || n == 12) ? 'two'
    : (n == 3 || n == 13) ? 'few'
    : 'other',
    "gl": a,
    "gsw": a,
    "gu": (n) => n == 1 ? 'one'
    : (n == 2 || n == 3) ? 'two'
    : n == 4 ? 'few'
    : n == 6 ? 'many'
    : 'other',
    "he": a,
    "hi": (n) => n == 1 ? 'one'
    : (n == 2 || n == 3) ? 'two'
    : n == 4 ? 'few'
    : n == 6 ? 'many'
    : 'other',
    "hr": a,
    "hsb": a,
    "hu": (n) => (n == 1 || n == 5) ? 'one' : 'other',
    "hy": b,
    "ia": a,
    "id": a,
    "ie": a,
    "is": a,
    "it": (n) => (n == 11 || n == 8 || n == 80 || n == 800) ? 'many' : 'other',
    "ja": a,
    "ka": (n) => {
  const s = String(n).split('.'), i = s[0], i100 = i.slice(-2);
  return i == 1 ? 'one'
    : i == 0 || ((i100 >= 2 && i100 <= 20) || i100 == 40 || i100 == 60 || i100 == 80) ? 'many'
    : 'other';
},
    "kk": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1);
  return n10 == 6 || n10 == 9 || t0 && n10 == 0 && n != 0 ? 'many' : 'other';
},
    "km": a,
    "kn": a,
    "ko": a,
    "kok": (n) => n == 1 ? 'one'
    : (n == 2 || n == 3) ? 'two'
    : n == 4 ? 'few'
    : 'other',
    "kok_Latn": (n) => n == 1 ? 'one'
    : (n == 2 || n == 3) ? 'two'
    : n == 4 ? 'few'
    : 'other',
    "kw": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n100 = t0 && s[0].slice(-2);
  return (t0 && n >= 1 && n <= 4) || ((n100 >= 1 && n100 <= 4) || (n100 >= 21 && n100 <= 24) || (n100 >= 41 && n100 <= 44) || (n100 >= 61 && n100 <= 64) || (n100 >= 81 && n100 <= 84)) ? 'one'
    : n == 5 || n100 == 5 ? 'many'
    : 'other';
},
    "ky": a,
    "lij": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n;
  return (n == 11 || n == 8 || (t0 && n >= 80 && n <= 89) || (t0 && n >= 800 && n <= 899)) ? 'many' : 'other';
},
    "lld": (n) => (n == 11 || n == 8 || n == 80 || n == 800) ? 'many' : 'other',
    "lo": b,
    "lt": a,
    "lv": a,
    "mk": (n) => {
  const s = String(n).split('.'), i = s[0], i10 = i.slice(-1), i100 = i.slice(-2);
  return i10 == 1 && i100 != 11 ? 'one'
    : i10 == 2 && i100 != 12 ? 'two'
    : (i10 == 7 || i10 == 8) && i100 != 17 && i100 != 18 ? 'many'
    : 'other';
},
    "ml": a,
    "mn": a,
    "mo": b,
    "mr": (n) => n == 1 ? 'one'
    : (n == 2 || n == 3) ? 'two'
    : n == 4 ? 'few'
    : 'other',
    "ms": b,
    "my": a,
    "nb": a,
    "ne": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n;
  return (t0 && n >= 1 && n <= 4) ? 'one' : 'other';
},
    "nl": a,
    "no": a,
    "or": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n;
  return (n == 1 || n == 5 || (t0 && n >= 7 && n <= 9)) ? 'one'
    : (n == 2 || n == 3) ? 'two'
    : n == 4 ? 'few'
    : n == 6 ? 'many'
    : 'other';
},
    "pa": a,
    "pl": a,
    "prg": a,
    "ps": a,
    "pt": a,
    "ro": b,
    "ru": a,
    "sc": (n) => (n == 11 || n == 8 || n == 80 || n == 800) ? 'many' : 'other',
    "scn": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n;
  return (n == 11 || n == 8 || (t0 && n >= 80 && n <= 89) || (t0 && n >= 800 && n <= 899)) ? 'many' : 'other';
},
    "sd": a,
    "sh": a,
    "si": a,
    "sk": a,
    "sl": a,
    "sq": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
  return n == 1 ? 'one'
    : n10 == 4 && n100 != 14 ? 'many'
    : 'other';
},
    "sr": a,
    "sv": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
  return (n10 == 1 || n10 == 2) && n100 != 11 && n100 != 12 ? 'one' : 'other';
},
    "sw": a,
    "ta": a,
    "te": a,
    "th": a,
    "tk": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1);
  return (n10 == 6 || n10 == 9) || n == 10 ? 'few' : 'other';
},
    "tl": b,
    "tpi": a,
    "tr": a,
    "uk": (n) => {
  const s = String(n).split('.'), t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
  return n10 == 3 && n100 != 13 ? 'few' : 'other';
},
    "und": a,
    "ur": a,
    "uz": a,
    "vec": (n) => (n == 11 || n == 8 || n == 80 || n == 800) ? 'many' : 'other',
    "vi": b,
    "yue": a,
    "zh": a,
    "zu": a
  };
})();

/* range: 91 locales */
var PLURAL_RANGE = (function () {
const a = (start, end) => "other";
const b = (start, end) => (start === "other" && end === "one") ? "one" : "other";
const c = (start, end) => end || "other";
  return {
    "af": a,
    "ak": b,
    "am": c,
    "an": a,
    "ar": (start, end) => (
  end === "few" ? "few"
  : end === "many" ? "many"
  : (start === "zero" && end === "one") ? "zero"
  : (start === "zero" && end === "two") ? "zero"
  : "other"
),
    "as": c,
    "az": c,
    "be": c,
    "bg": a,
    "bn": c,
    "bs": c,
    "ca": a,
    "cs": c,
    "cy": c,
    "da": c,
    "de": c,
    "el": c,
    "en": a,
    "es": a,
    "et": a,
    "eu": a,
    "fa": b,
    "fi": a,
    "fil": c,
    "fr": c,
    "ga": c,
    "gl": c,
    "gsw": c,
    "gu": c,
    "he": a,
    "hi": c,
    "hr": c,
    "hu": c,
    "hy": c,
    "ia": a,
    "id": a,
    "io": a,
    "is": c,
    "it": c,
    "ja": a,
    "ka": (start, end) => start || "other",
    "kk": c,
    "km": a,
    "kn": c,
    "ko": a,
    "ky": c,
    "lij": c,
    "lo": a,
    "lt": c,
    "lv": (start, end) => end === "one" ? "one" : "other",
    "mk": a,
    "ml": c,
    "mn": c,
    "mr": c,
    "ms": a,
    "my": a,
    "nb": a,
    "ne": c,
    "nl": c,
    "no": a,
    "or": b,
    "pa": c,
    "pcm": a,
    "pl": c,
    "ps": c,
    "pt": c,
    "ro": (start, end) => end === "few" ? "few" : end === "one" ? "few" : "other",
    "ru": c,
    "sc": c,
    "scn": c,
    "sd": b,
    "si": (start, end) => (start === "one" && end === "one") ? "one" : "other",
    "sk": c,
    "sl": (start, end) => (
  end === "few" ? "few"
  : end === "one" ? "few"
  : end === "two" ? "two"
  : "other"
),
    "sq": c,
    "sr": c,
    "sv": a,
    "sw": c,
    "ta": c,
    "te": c,
    "th": a,
    "tk": c,
    "tr": c,
    "ug": c,
    "uk": c,
    "ur": a,
    "uz": c,
    "vi": a,
    "yue": a,
    "zh": a,
    "zu": c
  };
})();

/* categories: 224 locales */
var PLURAL_CATEGORIES = (function () {
const z = "zero", o = "one", t = "two", f = "few", m = "many", x = "other";
const a = {cardinal:[o,x],ordinal:[x]};
const b = {cardinal:[o,x],ordinal:[o,x]};
const c = {cardinal:[x],ordinal:[x]};
const d = {cardinal:[o,t,x],ordinal:[x]};
  return {
    "af": a,
    "ak": a,
    "am": a,
    "an": a,
    "ar": {cardinal:[z,o,t,f,m,x],ordinal:[x]},
    "ars": {cardinal:[z,o,t,f,m,x],ordinal:[x]},
    "as": {cardinal:[o,x],ordinal:[o,t,f,m,x]},
    "asa": a,
    "ast": a,
    "az": {cardinal:[o,x],ordinal:[o,f,m,x]},
    "bal": b,
    "be": {cardinal:[o,f,m,x],ordinal:[f,x]},
    "bem": a,
    "bez": a,
    "bg": a,
    "bho": a,
    "blo": {cardinal:[z,o,x],ordinal:[z,o,f,x]},
    "bm": c,
    "bn": {cardinal:[o,x],ordinal:[o,t,f,m,x]},
    "bo": c,
    "br": {cardinal:[o,t,f,m,x],ordinal:[x]},
    "brx": a,
    "bs": {cardinal:[o,f,x],ordinal:[x]},
    "ca": {cardinal:[o,m,x],ordinal:[o,t,f,x]},
    "ce": a,
    "ceb": a,
    "cgg": a,
    "chr": a,
    "ckb": a,
    "cs": {cardinal:[o,f,m,x],ordinal:[x]},
    "csw": a,
    "cv": {cardinal:[z,o,x],ordinal:[x]},
    "cy": {cardinal:[z,o,t,f,m,x],ordinal:[z,o,t,f,m,x]},
    "da": a,
    "de": a,
    "doi": a,
    "dsb": {cardinal:[o,t,f,x],ordinal:[x]},
    "dv": a,
    "dz": c,
    "ee": a,
    "el": a,
    "en": {cardinal:[o,x],ordinal:[o,t,f,x]},
    "eo": a,
    "es": {cardinal:[o,m,x],ordinal:[x]},
    "et": a,
    "eu": a,
    "fa": a,
    "ff": a,
    "fi": a,
    "fil": b,
    "fo": a,
    "fr": {cardinal:[o,m,x],ordinal:[o,x]},
    "fur": a,
    "fy": a,
    "ga": {cardinal:[o,t,f,m,x],ordinal:[o,x]},
    "gd": {cardinal:[o,t,f,x],ordinal:[o,t,f,x]},
    "gl": a,
    "gsw": a,
    "gu": {cardinal:[o,x],ordinal:[o,t,f,m,x]},
    "guw": a,
    "gv": {cardinal:[o,t,f,m,x],ordinal:[x]},
    "ha": a,
    "haw": a,
    "he": d,
    "hi": {cardinal:[o,x],ordinal:[o,t,f,m,x]},
    "hnj": c,
    "hr": {cardinal:[o,f,x],ordinal:[x]},
    "hsb": {cardinal:[o,t,f,x],ordinal:[x]},
    "hu": b,
    "hy": b,
    "ia": a,
    "id": c,
    "ie": a,
    "ig": c,
    "ii": c,
    "io": a,
    "is": a,
    "it": {cardinal:[o,m,x],ordinal:[m,x]},
    "iu": d,
    "ja": c,
    "jbo": c,
    "jgo": a,
    "jmc": a,
    "jv": c,
    "jw": c,
    "ka": {cardinal:[o,x],ordinal:[o,m,x]},
    "kab": a,
    "kaj": a,
    "kcg": a,
    "kde": c,
    "kea": c,
    "kk": {cardinal:[o,x],ordinal:[m,x]},
    "kkj": a,
    "kl": a,
    "km": c,
    "kn": a,
    "ko": c,
    "kok": {cardinal:[o,x],ordinal:[o,t,f,x]},
    "kok_Latn": {cardinal:[o,x],ordinal:[o,t,f,x]},
    "ks": a,
    "ksb": a,
    "ksh": {cardinal:[z,o,x],ordinal:[x]},
    "ku": a,
    "kw": {cardinal:[z,o,t,f,m,x],ordinal:[o,m,x]},
    "ky": a,
    "lag": {cardinal:[z,o,x],ordinal:[x]},
    "lb": a,
    "lg": a,
    "lij": {cardinal:[o,x],ordinal:[m,x]},
    "lkt": c,
    "lld": {cardinal:[o,m,x],ordinal:[m,x]},
    "ln": a,
    "lo": {cardinal:[x],ordinal:[o,x]},
    "lt": {cardinal:[o,f,m,x],ordinal:[x]},
    "lv": {cardinal:[z,o,x],ordinal:[x]},
    "mas": a,
    "mg": a,
    "mgo": a,
    "mk": {cardinal:[o,x],ordinal:[o,t,m,x]},
    "ml": a,
    "mn": a,
    "mo": {cardinal:[o,f,x],ordinal:[o,x]},
    "mr": {cardinal:[o,x],ordinal:[o,t,f,x]},
    "ms": {cardinal:[x],ordinal:[o,x]},
    "mt": {cardinal:[o,t,f,m,x],ordinal:[x]},
    "my": c,
    "nah": a,
    "naq": d,
    "nb": a,
    "nd": a,
    "ne": b,
    "nl": a,
    "nn": a,
    "nnh": a,
    "no": a,
    "nqo": c,
    "nr": a,
    "nso": a,
    "ny": a,
    "nyn": a,
    "om": a,
    "or": {cardinal:[o,x],ordinal:[o,t,f,m,x]},
    "os": a,
    "osa": c,
    "pa": a,
    "pap": a,
    "pcm": a,
    "pl": {cardinal:[o,f,m,x],ordinal:[x]},
    "prg": {cardinal:[z,o,x],ordinal:[x]},
    "ps": a,
    "pt": {cardinal:[o,m,x],ordinal:[x]},
    "pt_PT": {cardinal:[o,m,x],ordinal:[x]},
    "rm": a,
    "ro": {cardinal:[o,f,x],ordinal:[o,x]},
    "rof": a,
    "ru": {cardinal:[o,f,m,x],ordinal:[x]},
    "rwk": a,
    "sah": c,
    "saq": a,
    "sat": d,
    "sc": {cardinal:[o,x],ordinal:[m,x]},
    "scn": {cardinal:[o,m,x],ordinal:[m,x]},
    "sd": a,
    "sdh": a,
    "se": d,
    "seh": a,
    "ses": c,
    "sg": c,
    "sgs": {cardinal:[o,t,f,m,x],ordinal:[x]},
    "sh": {cardinal:[o,f,x],ordinal:[x]},
    "shi": {cardinal:[o,f,x],ordinal:[x]},
    "si": a,
    "sk": {cardinal:[o,f,m,x],ordinal:[x]},
    "sl": {cardinal:[o,t,f,x],ordinal:[x]},
    "sma": d,
    "smi": d,
    "smj": d,
    "smn": d,
    "sms": d,
    "sn": a,
    "so": a,
    "sq": {cardinal:[o,x],ordinal:[o,m,x]},
    "sr": {cardinal:[o,f,x],ordinal:[x]},
    "ss": a,
    "ssy": a,
    "st": a,
    "su": c,
    "sv": b,
    "sw": a,
    "syr": a,
    "ta": a,
    "te": a,
    "teo": a,
    "th": c,
    "ti": a,
    "tig": a,
    "tk": {cardinal:[o,x],ordinal:[f,x]},
    "tl": b,
    "tn": a,
    "to": c,
    "tpi": c,
    "tr": a,
    "ts": a,
    "tzm": a,
    "ug": a,
    "uk": {cardinal:[o,f,m,x],ordinal:[f,x]},
    "und": c,
    "ur": a,
    "uz": a,
    "ve": a,
    "vec": {cardinal:[o,m,x],ordinal:[m,x]},
    "vi": {cardinal:[x],ordinal:[o,x]},
    "vo": a,
    "vun": a,
    "wa": a,
    "wae": a,
    "wo": c,
    "xh": a,
    "xog": a,
    "yi": a,
    "yo": c,
    "yue": c,
    "zh": c,
    "zu": a
  };
})();

var PLURAL_DATA = {
  cardinal: PLURAL_CARDINAL,
  ordinal: PLURAL_ORDINAL,
  range: PLURAL_RANGE,
  categories: PLURAL_CATEGORIES
};
