/*
 * Copyright (c) Ammar Ahmed.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * react-native-quickjs-intl — the engine-facing half.
 *
 * PURPOSE
 *   Installs `globalThis.Intl` lazily and provides the JavaScript layer with a
 *   small object of native functions that reach the platform's CLDR database.
 *
 * THREE THINGS THIS FILE EXISTS TO DO
 *
 *   1. **Lazy first-use materialization from a module.** The engine gets this
 *      from JS_DefineAutoInitProperty, which is internal to quickjs.c and not
 *      in quickjs.h. The same effect is reachable from public API only:
 *      JS_DefinePropertyGetSet installs an accessor, and on first read the
 *      getter deserializes a precompiled bytecode blob with JS_ReadObject,
 *      evaluates it with JS_EvalFunction, and redefines `Intl` as a plain data
 *      property. Every later access is an ordinary property read.
 *
 *      MEASURED (bench/spikes/intl/self-replacing-accessor.c, M4 Pro,
 *      2026-07-26): an app that never touches Intl pays **152 ns once per
 *      runtime**, against a JS_NewRuntime+JS_NewContext floor of ~54 us. The
 *      getter is js_dup'd by the engine before it is called
 *      (vendor/quickjs-ng/quickjs.c:10376, whose comment reads "the field could
 *      be removed in the getter"), so replacing the property from inside its
 *      own getter is supported rather than merely observed to work.
 *
 *   2. **Real constructors.** A jsi::Function from createFromHostFunction is
 *      not a constructor. `new` against it does not produce an empty object —
 *      it produces no instance at all: `thisVal` is the constructor function
 *      itself, so writes to `this` mutate the constructor, and the result is
 *      whatever the host function returned, or `undefined` if it returned
 *      nothing. Return an object explicitly and its prototype is
 *      Object.prototype, so the assigned `.prototype` is never consulted and
 *      `instanceof` is false; `class S extends Thing {}` yields `undefined`
 *      from `new S()` rather than throwing. MEASURED.
 *      `Intl` is constructor-heavy, so this module does not use JSI for its
 *      class shapes at all. The shapes are declared as ordinary JavaScript in
 *      the precompiled blob, which the engine compiles into genuine
 *      constructors — `new`, `.prototype`, `instanceof` and subclassing all
 *      work with no special handling. Where a native constructor is needed,
 *      JS_NewCFunction2 with JS_CFUNC_constructor is available and is what
 *      would be used; stage one needs none.
 *
 *   3. **Deterministic release of platform formatters.** An NSDateFormatter or
 *      an android.icu.text.DateFormat is expensive and must not leak. Each
 *      handle lives in a JSValue of a dedicated JSClass whose finalizer calls
 *      dtf_close, so lifetime follows QuickJS's refcounting exactly and a
 *      formatter is released at the moment its JavaScript owner is.
 *
 * WHAT THIS DELIBERATELY DOES NOT DO
 *   - No ECMA-402 semantics. Not one option name, not one part type mapping
 *     decision, not one locale-negotiation rule lives here. All of it is in
 *     js/intl.js, so there is exactly one copy and it is the same on every
 *     platform.
 *   - No caching of formatters *except* the one place the option bag is a
 *     sound key: the fully-resolved NumberOptions that `nfOpen` already
 *     reads. Date/time caching stays in the backend, keyed by skeleton.
 *   - No thread affinity beyond the runtime's own. Every entry point here runs
 *     on the JS thread, called from JavaScript.
 */

#include <cstdio>
#include <cstring>
#include <memory>
#include <string>
#include <vector>

#include "IntlModuleC.h"
#include "IntlPlatform.h"
#include "quickjs.h"

// Generated by scripts/embed-js.js at build time. IntlBuildConfig.h defines
// RNQJS_INTL_HAVE_BLOB, which says whether a qjsc-ng from this engine revision
// was available; all three headers always exist so a missing one is a build
// wiring error rather than a silent fallback.
#include "IntlBlob.h"  // kIntlBlob / kIntlBlobSize
#include "IntlBuildConfig.h"
#include "IntlSource.h"  // kIntlSource

namespace rnqjs::intl {
namespace {

/* --------------------------------------------------------------------------
 * The formatter handle class
 * -------------------------------------------------------------------------- */

/*
 * A DateTimeFormatter lives in a JSValue of its own JSClass, so its lifetime is
 * the engine's refcounting and an NSDateFormatter or
 * android.icu.text.DateFormat is released at the moment its JavaScript owner
 * is. JS_NewClassID is process-global and JS_NewClass is per runtime, which is
 * why the id is a static initialised once and the class is registered into
 * every runtime.
 */
/*
 * One JSClass per handle type.
 *
 * A single shared class would be one class id and one finalizer, and it would
 * be wrong: JS_GetOpaque2 only checks the class id, so a shared class would let
 * `nfFormat(aCollator, 1)` static_cast a Collator to a NumberFormatter and call
 * through a garbage vtable. Distinct ids turn that into a clean TypeError, and
 * the JavaScript layer is not the only caller — the differential corpus passes
 * deliberately wrong handles.
 *
 * The template is what keeps five near-identical finalizers from being written
 * out five times; `Handle<T>::id` is a distinct static per T, which is exactly
 * the distinction being relied on.
 */
template <typename T>
struct Handle {
  static JSClassID id;
  static JSClassDef def;

  static void finalizer(JSRuntime * /*rt*/, JSValue val) {
    delete static_cast<T *>(JS_GetOpaque(val, id));
  }

  static void registerIn(JSRuntime *rt, const char *name) {
    if (id == 0) JS_NewClassID(rt, &id);
    def = JSClassDef{name, finalizer, nullptr, nullptr, nullptr};
    JS_NewClass(rt, id, &def);
  }

  static T *of(JSContext *ctx, JSValueConst v) {
    return static_cast<T *>(JS_GetOpaque2(ctx, v, id));
  }

  /// Wraps an owned pointer. Consumes `p` on success and on failure alike.
  static JSValue wrap(JSContext *ctx, std::unique_ptr<T> p) {
    if (!p) return JS_NULL;
    JSValue obj = JS_NewObjectClass(ctx, static_cast<int>(id));
    if (JS_IsException(obj)) return obj;  // ~unique_ptr releases the platform
    JS_SetOpaque(obj, p.release());
    return obj;
  }
};
template <typename T>
JSClassID Handle<T>::id = 0;
template <typename T>
JSClassDef Handle<T>::def{};

using DtfHandle = Handle<DateTimeFormatter>;
using NfHandle = Handle<NumberFormatter>;
using ColHandle = Handle<Collator>;
using RtfHandle = Handle<RelativeTimeFormatter>;
using LfHandle = Handle<ListFormatter>;

DateTimeFormatter *handleOf(JSContext *ctx, JSValueConst v) {
  return DtfHandle::of(ctx, v);
}

/* --------------------------------------------------------------------------
 * Small conversions
 * -------------------------------------------------------------------------- */

/// Reads a UTF-8 string argument. undefined and null both yield the empty
/// string, which is how the platform interface spells "not requested".
std::string utf8Arg(JSContext *ctx, JSValueConst v) {
  if (JS_IsUndefined(v) || JS_IsNull(v)) return {};
  const char *s = JS_ToCString(ctx, v);
  if (s == nullptr) return {};
  std::string out(s);
  JS_FreeCString(ctx, s);
  return out;
}

/**
 * A borrowed, engine-owned view of a JSValue's UTF-16 text.
 *
 * PURPOSE
 *   Hand the platform layer the characters QuickJS already holds instead of a
 *   private copy of them.
 *
 *   MOTIVATED BY docs/intl-native-placement.md, which decomposed
 *   `localeCompare` at 688 ns and found the largest single item — ~303 ns,
 *   44% — was not the collation and not the crossing but a conversion
 *   pipeline: `utf16Arg` allocated a `std::u16string` and copied into it, and
 *   `fromU16` then allocated an `NSString` and copied again. Six heap
 *   allocations and six full copies of two short ASCII strings before
 *   Foundation looked at anything.
 *
 * WHAT IT BORROWS FROM
 *   `JS_ToCStringLenUTF16` returns a pointer into a `JSString` whose reference
 *   it holds (vendor/quickjs-ng/quickjs.c:5708). For an already-wide string
 *   that is the *original* string's storage and costs nothing; for a narrow
 *   (Latin-1) string the engine allocates a widened copy first. Removing that
 *   second case needs an engine-side accessor for the narrow bytes and is
 *   therefore engine work, not module work — see the handoff note in
 *   docs/intl-string-seam.md.
 *
 * INVARIANTS
 *   - The view is valid only for the lifetime of the U16Borrow. Never store
 *     it, never return it, never let it outlive the JSValue's argument frame.
 *   - Non-copyable, so it cannot be captured by accident.
 *   - `ok()` is false exactly when the engine threw (ToString on a value with
 *     a throwing `toString`, or OOM). The caller must propagate JS_EXCEPTION;
 *     the older `utf16Arg` swallowed that case into an empty string.
 *   - The empty string yields a non-null pointer and size 0, so a consumer
 *     never has to null-check `view().data()`.
 *
 * WHAT IT DELIBERATELY DOES NOT DO
 *   It does not NUL-terminate, it does not transcode, and it does not accept
 *   undefined/null the way `utf8Arg` does. A caller that needs "absent means
 *   empty" semantics wants `utf8Arg`.
 */
class U16Borrow {
 public:
  U16Borrow(JSContext *ctx, JSValueConst v) : ctx_(ctx) {
    size_t len = 0;
    p_ = JS_ToCStringLenUTF16(ctx, &len, v);
    n_ = p_ != nullptr ? len : 0;
  }
  ~U16Borrow() {
    if (p_ != nullptr) JS_FreeCStringUTF16(ctx_, p_);
  }
  U16Borrow(const U16Borrow &) = delete;
  U16Borrow &operator=(const U16Borrow &) = delete;

  bool ok() const {
    return p_ != nullptr;
  }
  std::u16string_view view() const {
    return std::u16string_view(reinterpret_cast<const char16_t *>(p_), n_);
  }

 private:
  JSContext *ctx_;
  const uint16_t *p_ = nullptr;
  size_t n_ = 0;
};

JSValue makeString(JSContext *ctx, const std::u16string &s) {
  return JS_NewStringUTF16(
      ctx, reinterpret_cast<const uint16_t *>(s.data()), s.size());
}

/// An empty platform answer means "no opinion" and becomes null, not "".
JSValue emitOptional(JSContext *ctx, const std::string &s) {
  return s.empty() ? JS_NULL : JS_NewStringLen(ctx, s.data(), s.size());
}

JSValue makeArray(JSContext *ctx, const std::vector<std::string> &v) {
  JSValue arr = JS_NewArray(ctx);
  for (uint32_t i = 0; i < v.size(); i++) {
    JS_SetPropertyUint32(
        ctx, arr, i, JS_NewStringLen(ctx, v[i].data(), v[i].size()));
  }
  return arr;
}

/* --------------------------------------------------------------------------
 * Native functions handed to the JS layer
 * -------------------------------------------------------------------------- */

JSValue js_backendName(JSContext *ctx, JSValueConst, int, JSValueConst *) {
  return JS_NewString(ctx, platform()->name());
}

JSValue js_availableLocales(JSContext *ctx, JSValueConst, int, JSValueConst *) {
  return makeArray(ctx, platform()->availableLocales());
}

JSValue js_defaultLocale(JSContext *ctx, JSValueConst, int, JSValueConst *) {
  return emitOptional(ctx, platform()->defaultLocale());
}

JSValue js_defaultTimeZone(JSContext *ctx, JSValueConst, int, JSValueConst *) {
  return emitOptional(ctx, platform()->defaultTimeZone());
}

JSValue js_canonicalize(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 1) return JS_NULL;
  return emitOptional(ctx, platform()->canonicalize(utf8Arg(ctx, argv[0])));
}

JSValue js_maximize(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 1) return JS_NULL;
  return emitOptional(ctx, platform()->maximize(utf8Arg(ctx, argv[0])));
}

JSValue js_minimize(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 1) return JS_NULL;
  return emitOptional(ctx, platform()->minimize(utf8Arg(ctx, argv[0])));
}

JSValue js_normalizeTimeZone(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 1) return JS_NULL;
  return emitOptional(
      ctx, platform()->normalizeTimeZone(utf8Arg(ctx, argv[0])));
}

JSValue js_timeZones(JSContext *ctx, JSValueConst, int, JSValueConst *) {
  return makeArray(ctx, platform()->timeZones());
}

JSValue js_calendars(JSContext *ctx, JSValueConst, int, JSValueConst *) {
  return makeArray(ctx, platform()->calendars());
}

JSValue js_numberingSystems(JSContext *ctx, JSValueConst, int, JSValueConst *) {
  return makeArray(ctx, platform()->numberingSystems());
}

/*
 * dtfOpen(locale, calendar, numberingSystem, timeZone, hourCycle, skeleton,
 *         dateStyle, timeStyle) -> handle | null
 *
 * Eight positional arguments rather than an options object, deliberately. This
 * crosses once per formatter and never per format() call, so its cost is
 * irrelevant; what matters is that the platform layer receives a plain struct
 * and never reads a JavaScript object, which is what keeps the JNI and
 * Objective-C code free of any engine knowledge.
 */
JSValue js_dtfOpen(JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  auto arg = [&](int i) { return i < argc ? argv[i] : JS_UNDEFINED; };
  DateTimeOptions opts;
  opts.locale = utf8Arg(ctx, arg(0));
  opts.calendar = utf8Arg(ctx, arg(1));
  opts.numberingSystem = utf8Arg(ctx, arg(2));
  opts.timeZone = utf8Arg(ctx, arg(3));
  opts.hourCycle = utf8Arg(ctx, arg(4));
  opts.skeleton = utf8Arg(ctx, arg(5));
  opts.dateStyle = utf8Arg(ctx, arg(6));
  opts.timeStyle = utf8Arg(ctx, arg(7));
  if (opts.locale.empty()) return JS_NULL;

  std::unique_ptr<DateTimeFormatter> dtf = platform()->openDateTimeFormat(opts);
  if (!dtf) return JS_NULL;

  return DtfHandle::wrap(ctx, std::move(dtf));
}

JSValue js_dtfFormat(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) return JS_ThrowTypeError(ctx, "dtfFormat expects (handle, ms)");
  DateTimeFormatter *dtf = handleOf(ctx, argv[0]);
  if (dtf == nullptr) return JS_EXCEPTION;
  double ms = 0;
  if (JS_ToFloat64(ctx, &ms, argv[1]) < 0) return JS_EXCEPTION;
  std::u16string out;
  if (!dtf->format(ms, out)) {
    return JS_ThrowRangeError(ctx, "date formatting failed");
  }
  return makeString(ctx, out);
}

/*
 * Part type names, indexed by PartType. The static_assert is the whole of the
 * protection against this drifting from the enum in IntlPlatform.h, and it is
 * enough: adding a type without adding a name here fails the build.
 */
const char *const kPartTypeNames[] = {
    "literal",
    "era",
    "year",
    "relatedYear",
    "yearName",
    "month",
    "day",
    "weekday",
    "dayPeriod",
    "hour",
    "minute",
    "second",
    "fractionalSecond",
    "timeZoneName",
    "unknown",
    "integer",
    "group",
    "decimal",
    "fraction",
    "currency",
    "percentSign",
    "plusSign",
    "minusSign",
    "nan",
    "infinity",
    "compact",
    "exponentSeparator",
    "exponentMinusSign",
    "exponentInteger",
    "unit",
    "element",
};
static_assert(
    sizeof(kPartTypeNames) / sizeof(kPartTypeNames[0]) ==
        static_cast<size_t>(PartType::Count),
    "kPartTypeNames is out of sync with PartType");

/**
 * FormattedParts -> `[{type, value}, ...]`.
 *
 * Every offset is clamped rather than trusted. A backend that miscomputes an
 * offset should produce a wrong string, not an out-of-bounds read, and this is
 * the only place a platform's arithmetic becomes a memory access.
 */
JSValue partsToArray(JSContext *ctx, const FormattedParts &p) {
  const auto textLen = static_cast<int32_t>(p.text.size());
  JSValue arr = JS_NewArray(ctx);
  for (size_t i = 0; i < p.parts.size(); i++) {
    const Part &part = p.parts[i];
    auto type = static_cast<int32_t>(part.type);
    if (type < 0 || type >= static_cast<int32_t>(PartType::Count)) {
      type = static_cast<int32_t>(PartType::Unknown);
    }
    int32_t begin = part.begin < 0 ? 0 : part.begin;
    if (begin > textLen) begin = textLen;
    int32_t end = part.end > textLen ? textLen : part.end;
    if (end < begin) end = begin;

    JSValue o = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, o, "type", JS_NewString(ctx, kPartTypeNames[type]));
    JS_SetPropertyStr(
        ctx, o, "value",
        JS_NewStringUTF16(
            ctx, reinterpret_cast<const uint16_t *>(p.text.data()) + begin,
            static_cast<size_t>(end - begin)));
    JS_SetPropertyUint32(ctx, arr, static_cast<uint32_t>(i), o);
  }
  return arr;
}

JSValue js_dtfFormatToParts(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) {
    return JS_ThrowTypeError(ctx, "dtfFormatToParts expects (handle, ms)");
  }
  DateTimeFormatter *dtf = handleOf(ctx, argv[0]);
  if (dtf == nullptr) return JS_EXCEPTION;
  double ms = 0;
  if (JS_ToFloat64(ctx, &ms, argv[1]) < 0) return JS_EXCEPTION;

  FormattedParts p;
  if (!dtf->formatToParts(ms, p)) {
    return JS_ThrowRangeError(ctx, "date formatting failed");
  }
  return partsToArray(ctx, p);
}

/*
 * dtfResolved(handle, key) -> string | null
 *
 * One entry point rather than six, because these are read once per construction
 * and never in a loop, and six function objects per runtime is five more than
 * the shape justifies.
 */
JSValue js_dtfResolved(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) return JS_NULL;
  DateTimeFormatter *dtf = handleOf(ctx, argv[0]);
  if (dtf == nullptr) return JS_EXCEPTION;
  return emitOptional(ctx, dtf->resolved(utf8Arg(ctx, argv[1])));
}

/* --------------------------------------------------------------------------
 * Stage two: NumberFormat, Collator, RelativeTimeFormat, ListFormat,
 * DisplayNames, Segmenter, case mapping and the locale enumerations.
 * -------------------------------------------------------------------------- */

/*
 * These factories take a JavaScript *object* where dtfOpen takes eight
 * positional arguments, and the difference is deliberate rather than
 * inconsistent. NumberOptions has twenty fields; twenty positional arguments is
 * a shape where adding a field in the middle silently shifts every later one,
 * and this file has already shipped one bug of exactly that kind (the setter
 * registered under the wrong JSCFunctionEnum read its value out of the wrong
 * register). Reading named properties here costs one atom lookup per field,
 * once per formatter construction, and never on a format path.
 *
 * The platform layer still receives a plain struct and still never sees a
 * JSValue — that invariant is what keeps the Objective-C and JNI code out of
 * the engine's refcounting rules, and it is unchanged.
 */
std::string strField(JSContext *ctx, JSValueConst obj, const char *name) {
  JSValue v = JS_GetPropertyStr(ctx, obj, name);
  std::string out = utf8Arg(ctx, v);
  JS_FreeValue(ctx, v);
  return out;
}

int32_t intField(
    JSContext *ctx, JSValueConst obj, const char *name, int32_t fallback) {
  JSValue v = JS_GetPropertyStr(ctx, obj, name);
  if (JS_IsUndefined(v) || JS_IsNull(v)) {
    JS_FreeValue(ctx, v);
    return fallback;
  }
  int32_t out = fallback;
  if (JS_ToInt32(ctx, &out, v) < 0) out = fallback;
  JS_FreeValue(ctx, v);
  return out;
}

bool boolField(JSContext *ctx, JSValueConst obj, const char *name) {
  JSValue v = JS_GetPropertyStr(ctx, obj, name);
  const bool out = JS_ToBool(ctx, v) > 0;
  JS_FreeValue(ctx, v);
  return out;
}

std::u16string utf16Arg(JSContext *ctx, JSValueConst v) {
  size_t len = 0;
  const uint16_t *p = JS_ToCStringLenUTF16(ctx, &len, v);
  if (p == nullptr) return {};
  std::u16string out(reinterpret_cast<const char16_t *>(p), len);
  JS_FreeCStringUTF16(ctx, p);
  return out;
}

NumberOptions readNumberOptions(JSContext *ctx, JSValueConst o) {
  NumberOptions n;
  n.locale = strField(ctx, o, "locale");
  n.numberingSystem = strField(ctx, o, "numberingSystem");
  n.style = strField(ctx, o, "style");
  n.currency = strField(ctx, o, "currency");
  n.currencyDisplay = strField(ctx, o, "currencyDisplay");
  n.currencySign = strField(ctx, o, "currencySign");
  n.unit = strField(ctx, o, "unit");
  n.unitDisplay = strField(ctx, o, "unitDisplay");
  n.notation = strField(ctx, o, "notation");
  n.compactDisplay = strField(ctx, o, "compactDisplay");
  n.signDisplay = strField(ctx, o, "signDisplay");
  n.roundingMode = strField(ctx, o, "roundingMode");
  n.trailingZeroDisplay = strField(ctx, o, "trailingZeroDisplay");
  n.useGrouping = strField(ctx, o, "useGrouping");
  n.roundingType = strField(ctx, o, "roundingType");
  n.minimumIntegerDigits = intField(ctx, o, "minimumIntegerDigits", 1);
  n.minimumFractionDigits = intField(ctx, o, "minimumFractionDigits", -1);
  n.maximumFractionDigits = intField(ctx, o, "maximumFractionDigits", -1);
  n.minimumSignificantDigits = intField(ctx, o, "minimumSignificantDigits", -1);
  n.maximumSignificantDigits = intField(ctx, o, "maximumSignificantDigits", -1);
  n.roundingIncrement = intField(ctx, o, "roundingIncrement", 1);
  return n;
}

/*
 * The option bag is kept alongside the handle because formatToParts needs it:
 * naming a leftover run `currency` versus `unit` versus `compact` is a property
 * of the request, not of the text. Storing it here rather than passing it back
 * down from JavaScript on every formatToParts call means the classification can
 * never drift from the formatter that produced the string.
 */
struct NumberHandle {
  /* Shared so the C++-side cache can hand the same formatter to two distinct
     JS instances of NumberFormat; on eviction it survives as long as any
     handle still references it. */
  std::shared_ptr<NumberFormatter> fmt;
  NumberOptions options;
  NumberSymbols symbols;
  bool symbolsLoaded = false;

  const NumberSymbols &syms() {
    if (!symbolsLoaded) {
      fmt->symbols(symbols);
      symbolsLoaded = true;
    }
    return symbols;
  }
};
using NumHandle = Handle<NumberHandle>;

/*
 * Cache for NumberFormatter: `new Intl.NumberFormat(...)` reopens a
 * formatter that is a function of the fully-resolved options alone, so
 * identical requests share one (ctor-currency: 95.17 us -> 35.04 us on the
 * apple backend). Per JS thread, not per process — formatters are stateful
 * and two runtimes can sit on different threads — which matches the module's
 * threading contract with no lock. Fixed-size FIFO: a small working set is
 * reopened many times, so LRU bookkeeping buys nothing.
 */
static constexpr size_t kNumberFormatterCacheCap = 32;
struct NumberFormatterCacheEntry {
  NumberOptions options;
  std::shared_ptr<NumberFormatter> fmt;
};
static thread_local std::vector<NumberFormatterCacheEntry>
    gNumberFormatterCache;

static bool numberOptionsEqual(const NumberOptions &a, const NumberOptions &b) {
  return a.locale == b.locale && a.numberingSystem == b.numberingSystem &&
         a.style == b.style && a.currency == b.currency &&
         a.currencyDisplay == b.currencyDisplay &&
         a.currencySign == b.currencySign && a.unit == b.unit &&
         a.unitDisplay == b.unitDisplay && a.notation == b.notation &&
         a.compactDisplay == b.compactDisplay &&
         a.signDisplay == b.signDisplay && a.roundingMode == b.roundingMode &&
         a.trailingZeroDisplay == b.trailingZeroDisplay &&
         a.useGrouping == b.useGrouping && a.roundingType == b.roundingType &&
         a.minimumIntegerDigits == b.minimumIntegerDigits &&
         a.minimumFractionDigits == b.minimumFractionDigits &&
         a.maximumFractionDigits == b.maximumFractionDigits &&
         a.minimumSignificantDigits == b.minimumSignificantDigits &&
         a.maximumSignificantDigits == b.maximumSignificantDigits &&
         a.roundingIncrement == b.roundingIncrement;
}

JSValue js_nfOpen(JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 1 || !JS_IsObject(argv[0])) return JS_NULL;
  NumberOptions opts = readNumberOptions(ctx, argv[0]);
  if (opts.locale.empty()) return JS_NULL;
  std::shared_ptr<NumberFormatter> fmt;
  /* Linear scan is faster than a hash for the small working set, and the
     constant factor matters: this is the constructor path. */
  for (auto &e : gNumberFormatterCache) {
    if (numberOptionsEqual(e.options, opts)) {
      fmt = e.fmt;
      break;
    }
  }
  if (!fmt) {
    std::unique_ptr<NumberFormatter> made = platform()->openNumberFormat(opts);
    if (!made) return JS_NULL;
    fmt = std::move(made);
    if (gNumberFormatterCache.size() >= kNumberFormatterCacheCap) {
      gNumberFormatterCache.erase(gNumberFormatterCache.begin());
    }
    gNumberFormatterCache.push_back({opts, fmt});
  }
  auto h = std::make_unique<NumberHandle>();
  h->fmt = std::move(fmt);
  h->options = std::move(opts);
  return NumHandle::wrap(ctx, std::move(h));
}

/// nfFormat(handle, value, decimalString) -> string
JSValue js_nfFormat(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) return JS_ThrowTypeError(ctx, "nfFormat expects (handle, v)");
  NumberHandle *h = NumHandle::of(ctx, argv[0]);
  if (h == nullptr) return JS_EXCEPTION;
  double v = 0;
  if (JS_ToFloat64(ctx, &v, argv[1]) < 0) return JS_EXCEPTION;
  const std::string dec = argc > 2 ? utf8Arg(ctx, argv[2]) : std::string();
  uint32_t hints = NumberFormatter::kHintNone;
  if (argc > 3) {
    int32_t bits = 0;
    if (JS_ToInt32(ctx, &bits, argv[3]) < 0) return JS_EXCEPTION;
    hints = static_cast<uint32_t>(bits);
  }
  std::u16string out;
  if (!h->fmt->format(v, dec, hints, out)) {
    return JS_ThrowRangeError(ctx, "number formatting failed");
  }
  return makeString(ctx, out);
}

JSValue js_nfFormatToParts(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) {
    return JS_ThrowTypeError(ctx, "nfFormatToParts expects (handle, v)");
  }
  NumberHandle *h = NumHandle::of(ctx, argv[0]);
  if (h == nullptr) return JS_EXCEPTION;
  double v = 0;
  if (JS_ToFloat64(ctx, &v, argv[1]) < 0) return JS_EXCEPTION;
  const std::string dec = argc > 2 ? utf8Arg(ctx, argv[2]) : std::string();
  uint32_t hints = NumberFormatter::kHintNone;
  if (argc > 3) {
    int32_t bits = 0;
    if (JS_ToInt32(ctx, &bits, argv[3]) < 0) return JS_EXCEPTION;
    hints = static_cast<uint32_t>(bits);
  }
  std::u16string text;
  if (!h->fmt->format(v, dec, hints, text)) {
    return JS_ThrowRangeError(ctx, "number formatting failed");
  }
  FormattedParts p;
  numberFormatToParts(text, h->syms(), h->options, p);
  return partsToArray(ctx, p);
}

JSValue js_nfResolved(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) return JS_NULL;
  NumberHandle *h = NumHandle::of(ctx, argv[0]);
  if (h == nullptr) return JS_EXCEPTION;
  return emitOptional(ctx, h->fmt->resolved(utf8Arg(ctx, argv[1])));
}

/* ---- Collator ---------------------------------------------------------- */

JSValue js_colOpen(JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 1 || !JS_IsObject(argv[0])) return JS_NULL;
  CollatorOptions o;
  o.locale = strField(ctx, argv[0], "locale");
  o.usage = strField(ctx, argv[0], "usage");
  o.sensitivity = strField(ctx, argv[0], "sensitivity");
  o.caseFirst = strField(ctx, argv[0], "caseFirst");
  o.collation = strField(ctx, argv[0], "collation");
  o.numeric = boolField(ctx, argv[0], "numeric");
  o.ignorePunctuation = boolField(ctx, argv[0], "ignorePunctuation");
  if (o.locale.empty()) return JS_NULL;
  return ColHandle::wrap(ctx, platform()->openCollator(o));
}

JSValue js_colCompare(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 3) return JS_ThrowTypeError(ctx, "colCompare expects (h, a, b)");
  Collator *c = ColHandle::of(ctx, argv[0]);
  if (c == nullptr) return JS_EXCEPTION;
  /*
   * Borrowed, not copied. This is the hot path of `String.prototype.
   * localeCompare` and of every `Array.prototype.sort` comparator that uses
   * it, and the two `std::u16string` copies that used to be here were measured
   * as part of the ~303 ns C seam in docs/intl-native-placement.md.
   */
  // Ablation arm 3: return before either argument is read, so the arm measures
  // the JS shim, the bound call, js_call_c_function and ColHandle::of alone.
  if (RNQJS_ABL(3)) return JS_NewInt32(ctx, 0);
  const U16Borrow a(ctx, argv[1]);
  if (!a.ok()) return JS_EXCEPTION;
  const U16Borrow b(ctx, argv[2]);
  if (!b.ok()) return JS_EXCEPTION;
  // Ablation arm 4: arm 3 plus JS_ToCStringLenUTF16 on both arguments. The
  // difference between arms 4 and 3 is what reading the two strings costs.
  if (RNQJS_ABL(4)) {
    return JS_NewInt32(
        ctx, static_cast<int32_t>(a.view().size()) -
                 static_cast<int32_t>(b.view().size()));
  }
  return JS_NewInt32(ctx, c->compare(a.view(), b.view()));
}

JSValue js_colResolved(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) return JS_NULL;
  Collator *c = ColHandle::of(ctx, argv[0]);
  if (c == nullptr) return JS_EXCEPTION;
  return emitOptional(ctx, c->resolved(utf8Arg(ctx, argv[1])));
}

/* ---- RelativeTimeFormat ------------------------------------------------ */

JSValue js_rtfOpen(JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 1 || !JS_IsObject(argv[0])) return JS_NULL;
  RelativeTimeOptions o;
  o.locale = strField(ctx, argv[0], "locale");
  o.numberingSystem = strField(ctx, argv[0], "numberingSystem");
  o.numeric = strField(ctx, argv[0], "numeric");
  o.style = strField(ctx, argv[0], "style");
  if (o.locale.empty()) return JS_NULL;
  return RtfHandle::wrap(ctx, platform()->openRelativeTimeFormat(o));
}

/// rtfFormat(handle, value, unit) -> string | null. Null means "this platform
/// has no wording for this unit" (Apple: `quarter`), never an error.
JSValue js_rtfFormat(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 3) return JS_ThrowTypeError(ctx, "rtfFormat expects (h, v, unit)");
  RelativeTimeFormatter *f = RtfHandle::of(ctx, argv[0]);
  if (f == nullptr) return JS_EXCEPTION;
  double v = 0;
  if (JS_ToFloat64(ctx, &v, argv[1]) < 0) return JS_EXCEPTION;
  std::u16string out;
  if (!f->format(v, utf8Arg(ctx, argv[2]), out)) return JS_NULL;
  return makeString(ctx, out);
}

JSValue js_rtfResolved(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) return JS_NULL;
  RelativeTimeFormatter *f = RtfHandle::of(ctx, argv[0]);
  if (f == nullptr) return JS_EXCEPTION;
  return emitOptional(ctx, f->resolved(utf8Arg(ctx, argv[1])));
}

/* ---- ListFormat -------------------------------------------------------- */

JSValue js_lfOpen(JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 1 || !JS_IsObject(argv[0])) return JS_NULL;
  ListFormatOptions o;
  o.locale = strField(ctx, argv[0], "locale");
  o.type = strField(ctx, argv[0], "type");
  o.style = strField(ctx, argv[0], "style");
  if (o.locale.empty()) return JS_NULL;
  return LfHandle::wrap(ctx, platform()->openListFormat(o));
}

JSValue js_lfFormat(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) return JS_ThrowTypeError(ctx, "lfFormat expects (h, items)");
  ListFormatter *f = LfHandle::of(ctx, argv[0]);
  if (f == nullptr) return JS_EXCEPTION;
  JSValue lenv = JS_GetPropertyStr(ctx, argv[1], "length");
  uint32_t len = 0;
  if (JS_ToUint32(ctx, &len, lenv) < 0) {
    JS_FreeValue(ctx, lenv);
    return JS_EXCEPTION;
  }
  JS_FreeValue(ctx, lenv);
  std::vector<std::u16string> items;
  items.reserve(len);
  for (uint32_t i = 0; i < len; i++) {
    JSValue e = JS_GetPropertyUint32(ctx, argv[1], i);
    items.push_back(utf16Arg(ctx, e));
    JS_FreeValue(ctx, e);
  }
  std::u16string out;
  if (!f->format(items, out)) return JS_NULL;
  return makeString(ctx, out);
}

JSValue js_lfResolved(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) return JS_NULL;
  ListFormatter *f = LfHandle::of(ctx, argv[0]);
  if (f == nullptr) return JS_EXCEPTION;
  return emitOptional(ctx, f->resolved(utf8Arg(ctx, argv[1])));
}

/* ---- DisplayNames, Segmenter, case mapping ----------------------------- */

JSValue js_displayName(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 4) return JS_NULL;
  return emitOptional(
      ctx, platform()->displayName(
               utf8Arg(ctx, argv[0]), utf8Arg(ctx, argv[1]),
               utf8Arg(ctx, argv[2]), utf8Arg(ctx, argv[3])));
}

/*
 * segment(locale, granularity, text) -> flat Int32 array
 *   [begin0, end0, isWordLike0, begin1, ...]
 *
 * Flat rather than an array of objects, and offsets rather than substrings,
 * because a sentence-segmented paragraph is hundreds of segments and
 * Intl.Segmenter's iterator is lazy: the JavaScript layer slices the source
 * string only for the segments a caller actually pulls. Building N objects and
 * N strings here would pay for every segment whether or not it is read.
 */
JSValue js_segment(JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 3) return JS_NULL;
  const std::vector<Segment> segs = platform()->segment(
      utf8Arg(ctx, argv[0]), utf8Arg(ctx, argv[1]), utf16Arg(ctx, argv[2]));
  JSValue arr = JS_NewArray(ctx);
  uint32_t k = 0;
  for (const Segment &s : segs) {
    JS_SetPropertyUint32(ctx, arr, k++, JS_NewInt32(ctx, s.begin));
    JS_SetPropertyUint32(ctx, arr, k++, JS_NewInt32(ctx, s.end));
    JS_SetPropertyUint32(ctx, arr, k++, JS_NewInt32(ctx, s.isWordLike ? 1 : 0));
  }
  return arr;
}

JSValue js_caseMap(JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 3) return JS_NULL;
  return makeString(
      ctx, platform()->caseMap(
               utf8Arg(ctx, argv[0]), JS_ToBool(ctx, argv[1]) > 0,
               utf16Arg(ctx, argv[2])));
}

JSValue js_currencyDigits(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 1) return JS_NewInt32(ctx, -1);
  return JS_NewInt32(ctx, platform()->currencyDigits(utf8Arg(ctx, argv[0])));
}

JSValue js_collations(JSContext *ctx, JSValueConst, int, JSValueConst *) {
  return makeArray(ctx, platform()->collations());
}

JSValue js_currencies(JSContext *ctx, JSValueConst, int, JSValueConst *) {
  return makeArray(ctx, platform()->currencies());
}

/// localeList(locale, key) with key in
/// {calendars, numberingSystems, timeZones, collations}.
JSValue js_localeList(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) return JS_NULL;
  const std::string locale = utf8Arg(ctx, argv[0]);
  const std::string key = utf8Arg(ctx, argv[1]);
  Platform *p = platform();
  if (key == "calendars") return makeArray(ctx, p->localeCalendars(locale));
  if (key == "numberingSystems") {
    return makeArray(ctx, p->localeNumberingSystems(locale));
  }
  if (key == "timeZones") return makeArray(ctx, p->localeTimeZones(locale));
  if (key == "collations") return makeArray(ctx, p->localeCollations(locale));
  return JS_NULL;
}

/// localeString(locale, key) with key in {hourCycle, textDirection}.
JSValue js_localeString(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 2) return JS_NULL;
  const std::string locale = utf8Arg(ctx, argv[0]);
  const std::string key = utf8Arg(ctx, argv[1]);
  Platform *p = platform();
  if (key == "hourCycle") return emitOptional(ctx, p->localeHourCycle(locale));
  if (key == "textDirection") {
    return emitOptional(ctx, p->localeTextDirection(locale));
  }
  return JS_NULL;
}

/// weekInfo(locale) -> [firstDay, minimalDays, ...weekend] | null
JSValue js_weekInfo(
    JSContext *ctx, JSValueConst, int argc, JSValueConst *argv) {
  if (argc < 1) return JS_NULL;
  WeekInfo w;
  if (!platform()->localeWeekInfo(utf8Arg(ctx, argv[0]), w)) return JS_NULL;
  JSValue arr = JS_NewArray(ctx);
  uint32_t k = 0;
  JS_SetPropertyUint32(ctx, arr, k++, JS_NewInt32(ctx, w.firstDay));
  JS_SetPropertyUint32(ctx, arr, k++, JS_NewInt32(ctx, w.minimalDays));
  for (int32_t d : w.weekend) {
    JS_SetPropertyUint32(ctx, arr, k++, JS_NewInt32(ctx, d));
  }
  return arr;
}

const JSCFunctionListEntry kNativeFuncs[] = {
    JS_CFUNC_DEF("backendName", 0, js_backendName),
    JS_CFUNC_DEF("availableLocales", 0, js_availableLocales),
    JS_CFUNC_DEF("defaultLocale", 0, js_defaultLocale),
    JS_CFUNC_DEF("defaultTimeZone", 0, js_defaultTimeZone),
    JS_CFUNC_DEF("canonicalize", 1, js_canonicalize),
    JS_CFUNC_DEF("maximize", 1, js_maximize),
    JS_CFUNC_DEF("minimize", 1, js_minimize),
    JS_CFUNC_DEF("normalizeTimeZone", 1, js_normalizeTimeZone),
    JS_CFUNC_DEF("timeZones", 0, js_timeZones),
    JS_CFUNC_DEF("calendars", 0, js_calendars),
    JS_CFUNC_DEF("numberingSystems", 0, js_numberingSystems),
    JS_CFUNC_DEF("dtfOpen", 8, js_dtfOpen),
    JS_CFUNC_DEF("dtfFormat", 2, js_dtfFormat),
    JS_CFUNC_DEF("dtfFormatToParts", 2, js_dtfFormatToParts),
    JS_CFUNC_DEF("dtfResolved", 2, js_dtfResolved),
    JS_CFUNC_DEF("nfOpen", 1, js_nfOpen),
    JS_CFUNC_DEF("nfFormat", 4, js_nfFormat),
    JS_CFUNC_DEF("nfFormatToParts", 4, js_nfFormatToParts),
    JS_CFUNC_DEF("nfResolved", 2, js_nfResolved),
    JS_CFUNC_DEF("colOpen", 1, js_colOpen),
    JS_CFUNC_DEF("colCompare", 3, js_colCompare),
    JS_CFUNC_DEF("colResolved", 2, js_colResolved),
    JS_CFUNC_DEF("rtfOpen", 1, js_rtfOpen),
    JS_CFUNC_DEF("rtfFormat", 3, js_rtfFormat),
    JS_CFUNC_DEF("rtfResolved", 2, js_rtfResolved),
    JS_CFUNC_DEF("lfOpen", 1, js_lfOpen),
    JS_CFUNC_DEF("lfFormat", 2, js_lfFormat),
    JS_CFUNC_DEF("lfResolved", 2, js_lfResolved),
    JS_CFUNC_DEF("displayName", 4, js_displayName),
    JS_CFUNC_DEF("segment", 3, js_segment),
    JS_CFUNC_DEF("caseMap", 3, js_caseMap),
    JS_CFUNC_DEF("currencyDigits", 1, js_currencyDigits),
    JS_CFUNC_DEF("collations", 0, js_collations),
    JS_CFUNC_DEF("currencies", 0, js_currencies),
    JS_CFUNC_DEF("localeList", 2, js_localeList),
    JS_CFUNC_DEF("localeString", 2, js_localeString),
    JS_CFUNC_DEF("weekInfo", 1, js_weekInfo),
};

/* --------------------------------------------------------------------------
 * Materialization
 * -------------------------------------------------------------------------- */

#if defined(RNQJS_INTL_COUNTERS) && RNQJS_INTL_COUNTERS
/*
 * Hit-rate counters, off by default and free when off.
 *
 * `blobLoads` versus `sourceLoads` is the one that matters: this project has
 * shipped a fast path with zero hits before, and "the bytecode blob is being
 * used" is exactly the kind of claim that is easy to believe and wrong. If
 * sourceLoads is non-zero in a shipping build, the build-time compile step did
 * not run or the blob is stale, and the startup number in the docs is fiction.
 */
struct Counters {
  unsigned long accessorInstalls = 0;
  unsigned long materializations = 0;
  unsigned long blobLoads = 0;
  unsigned long sourceLoads = 0;
  unsigned long setterOverrides = 0;
};
Counters g_counters;
#define RNQJS_INTL_COUNT(field) (++g_counters.field)
#else
#define RNQJS_INTL_COUNT(field) ((void)0)
#endif

/**
 * Deserializes and evaluates the Intl JavaScript layer, returning the factory
 * function it evaluates to (owned).
 *
 * The blob is tried first and the source is the fallback. The fallback is not
 * defensive programming: QuickJS bytecode is only loadable by the engine build
 * that produced it, JS_ReadObject rejects a BC_VERSION mismatch with a clean
 * SyntaxError (vendor/quickjs-ng/quickjs.c:44091), and a module whose blob was
 * generated against a different engine revision must still work rather than
 * refusing to install Intl. The counters above are how you find out which path
 * a build is actually taking.
 */
JSValue loadFactory(JSContext *ctx) {
#if RNQJS_INTL_HAVE_BLOB
  JSValue fn =
      JS_ReadObject(ctx, kIntlBlob, kIntlBlobSize, JS_READ_OBJ_BYTECODE);
  if (!JS_IsException(fn)) {
    RNQJS_INTL_COUNT(blobLoads);
    return JS_EvalFunction(ctx, fn);
  }
  /* Swallow the SyntaxError; the source path below is a complete answer. */
  JS_FreeValue(ctx, JS_GetException(ctx));
#endif
  RNQJS_INTL_COUNT(sourceLoads);
  return JS_Eval(ctx, kIntlSource, strlen(kIntlSource), "rnqjs:intl", 0);
}

JSValue buildIntl(JSContext *ctx) {
  JSValue factory = loadFactory(ctx);
  if (JS_IsException(factory)) return factory;
  if (!JS_IsFunction(ctx, factory)) {
    JS_FreeValue(ctx, factory);
    return JS_ThrowInternalError(
        ctx, "Intl layer did not evaluate to a factory");
  }

  JSValue native = JS_NewObject(ctx);
  JS_SetPropertyFunctionList(
      ctx, native, kNativeFuncs,
      static_cast<int>(sizeof(kNativeFuncs) / sizeof(kNativeFuncs[0])));

  JSValue args[1] = {native};
  JSValue intl = JS_Call(ctx, factory, JS_UNDEFINED, 1, args);
  JS_FreeValue(ctx, native);
  JS_FreeValue(ctx, factory);
  RNQJS_INTL_COUNT(materializations);
  return intl;
}

int defineIntlData(JSContext *ctx, JSValue value /* consumed */) {
  JSValue global = JS_GetGlobalObject(ctx);
  JSAtom atom = JS_NewAtom(ctx, "Intl");
  /* The attributes ECMA-402 requires of globalThis.Intl. */
  int rc = JS_DefinePropertyValue(
      ctx, global, atom, value, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE);
  JS_FreeAtom(ctx, atom);
  JS_FreeValue(ctx, global);
  return rc;
}

JSValue intlGetter(
    JSContext *ctx, JSValueConst /*thisVal*/, int /*argc*/,
    JSValueConst * /*argv*/) {
  JSValue intl = buildIntl(ctx);
  if (JS_IsException(intl)) return intl;
  /*
   * Redefine the property from inside its own getter. Safe because the engine
   * duplicates the getter before calling it (quickjs.c:10376). Defining on the
   * global object rather than on the receiver means a read through an odd
   * receiver — Reflect.get(globalThis, 'Intl', someOtherObject) — cannot
   * install Intl somewhere else.
   */
  if (defineIntlData(ctx, JS_DupValue(ctx, intl)) < 0) {
    JS_FreeValue(ctx, intl);
    return JS_EXCEPTION;
  }
  return intl;
}

/**
 * The setter, which exists because `globalThis.Intl` must be **writable**.
 *
 * A getter-only accessor is not writable: assignment is a silent no-op in
 * sloppy mode and a TypeError in strict mode. Every polyfill that feature-
 * detects and then installs itself — which is precisely what formatjs's
 * should-polyfill path does — assigns over globalThis.Intl, so a getter-only
 * accessor would turn "app installs a polyfill" into "app throws". This was
 * measured as a failing case in the spike before the setter existed.
 *
 * Assignment never materializes the blob: a caller assigning over Intl does not
 * want ours.
 *
 * Registered as JS_CFUNC_generic, not JS_CFUNC_setter. Those protos have their
 * own C signatures — (ctx, this_val) and (ctx, this_val, val) — and registering
 * a 4-argument generic function under them reads the value out of the wrong
 * register, storing `undefined` with no error anywhere. The spike hit exactly
 * that.
 */
JSValue intlSetter(
    JSContext *ctx, JSValueConst /*thisVal*/, int argc, JSValueConst *argv) {
  RNQJS_INTL_COUNT(setterOverrides);
  JSValue v = argc > 0 ? JS_DupValue(ctx, argv[0]) : JS_UNDEFINED;
  return defineIntlData(ctx, v) < 0 ? JS_EXCEPTION : JS_UNDEFINED;
}

}  // namespace

/* --------------------------------------------------------------------------
 * The ECMAScript-side entry points into ECMA-402
 * -------------------------------------------------------------------------- */

/*
 * `(1234.5).toLocaleString()`, `"a".localeCompare("b")`,
 * `new Date().toLocaleDateString()` and the two locale case mappings are what
 * an application actually calls. js/intl.js replaces all of them — but it only
 * runs when `Intl` is first *read*, and a program that calls
 * `(1234.5).toLocaleString("de")` without ever mentioning `Intl` never triggers
 * that read.
 *
 * MEASURED, and it was a real bug rather than a hypothetical one:
 *
 *   $ intl-cli-apple -e '''print((88776655n).toLocaleString("en",{maximumSignificantDigits:4}));
 *                         print(new Intl.NumberFormat("en",{maximumSignificantDigits:4}).format(88776655n));
 *                         print((12345n).toLocaleString("en"));'''
 *   88776655        <- the engine'''s stub: options ignored
 *   88,780,000      <- reading Intl materialized the layer
 *   12,345          <- the same call, now correct
 *
 * The first and third lines are the same call with different answers, and the
 * only difference is whether `Intl` had been touched. Three test262 files see
 * it; an application would see it far more often, because the whole point of
 * this module is that installing it changes the behaviour of code that never
 * mentions `Intl`.
 *
 * THE FIX, AND WHY IT IS A TRAMPOLINE RATHER THAN AN EAGER INSTALL
 *   Installing the real implementations at module-install time would mean
 *   materializing the whole ECMA-402 layer in every runtime, which is exactly
 *   the 67 us this design pays 152 ns to avoid. So each method is replaced with
 *   a tiny native trampoline that, on its first call, reads `globalThis.Intl`
 *   (running the accessor and therefore installing the real methods) and then
 *   re-dispatches. From the second call onwards the trampoline is gone: the
 *   property holds the JavaScript implementation.
 *
 *   The engine'''s original method is carried in the trampoline'''s own function
 *   data, so the one case where materialization does not replace the property —
 *   an application that assigned over `globalThis.Intl` before calling any of
 *   these, which suppresses our layer by design — degrades to the engine'''s
 *   locale-ignoring behaviour instead of recursing forever. That is the same
 *   behaviour the application would have had without this module.
 */
struct LocaleHook {
  const char *constructorName;
  const char *methodName;
  int length;
  /**
   * %TypedArray%.prototype has no global binding, so it is reached as the
   * prototype *of* Int8Array.prototype. Spelling that here rather than
   * hard-coding a second lookup path keeps every hook in one table, which is
   * what makes the table checkable by reading it.
   */
  bool viaPrototypeOfPrototype;
};

const LocaleHook kLocaleHooks[] = {
    {"Number", "toLocaleString", 0, false},
    {"BigInt", "toLocaleString", 0, false},
    {"String", "localeCompare", 1, false},
    {"String", "toLocaleUpperCase", 0, false},
    {"String", "toLocaleLowerCase", 0, false},
    {"Date", "toLocaleString", 0, false},
    {"Date", "toLocaleDateString", 0, false},
    {"Date", "toLocaleTimeString", 0, false},
    /*
     * Array and %TypedArray%. ECMA-402 requires these to forward `locales` and
     * `options` to each element's own toLocaleString; the plain ECMAScript
     * versions in the engine call it with no arguments. MEASURED:
     * `[0].toLocaleString("th-u-nu-thai", {minimumFractionDigits: 3})` returned
     * "0" where `(0).toLocaleString(...)` returned Thai digits — the two sides
     * of test262's own assertion.
     */
    {"Array", "toLocaleString", 0, false},
    {"Int8Array", "toLocaleString", 0, true},
};

/// The prototype object a hook installs onto, or JS_UNDEFINED.
JSValue prototypeFor(
    JSContext *ctx, JSValueConst global, const LocaleHook &hook) {
  JSValue ctor = JS_GetPropertyStr(ctx, global, hook.constructorName);
  if (!JS_IsObject(ctor)) {
    /* BigInt is absent from a build compiled without it, and a build without
       typed arrays has no Int8Array. Skipping is correct: there is no prototype
       to hook. */
    JS_FreeValue(ctx, ctor);
    return JS_UNDEFINED;
  }
  JSValue proto = JS_GetPropertyStr(ctx, ctor, "prototype");
  JS_FreeValue(ctx, ctor);
  if (hook.viaPrototypeOfPrototype && JS_IsObject(proto)) {
    JSValue outer = JS_GetPrototype(ctx, proto);
    JS_FreeValue(ctx, proto);
    proto = outer;
  }
  return proto;
}

JSValue localeTrampoline(
    JSContext *ctx, JSValueConst thisVal, int argc, JSValueConst *argv,
    int magic, JSValue *funcData) {
  const LocaleHook &hook = kLocaleHooks[magic];

  JSValue global = JS_GetGlobalObject(ctx);
  /* Reading the property is what runs the accessor and materializes the layer. */
  JSValue intl = JS_GetPropertyStr(ctx, global, "Intl");

  /*
   * Did OUR layer run?
   *
   * `__rnqjsBackend` is the diagnostics hook js/intl.js installs on the Intl
   * namespace, and its presence is the discriminator. It is needed because
   * `globalThis.Intl` is writable by design — a feature-detecting polyfill
   * assigns over it, which turns the accessor into a data property and means
   * our layer never runs and never replaces these prototype methods. Without
   * this check the trampoline would look itself up and recurse forever.
   *
   * The alternative discriminators were all worse: comparing the looked-up
   * function against the trampoline needs a self-reference (a retain cycle, and
   * two constructions to obtain), and a recursion-depth counter cannot survive
   * into the dispatched call without also suppressing the legitimate re-entry
   * of Array.prototype.toLocaleString.
   */
  bool ours = false;
  if (JS_IsObject(intl)) {
    JSValue probe = JS_GetPropertyStr(ctx, intl, "__rnqjsBackend");
    ours = JS_IsFunction(ctx, probe);
    JS_FreeValue(ctx, probe);
  }
  JS_FreeValue(ctx, intl);

  JSValue target = JS_UNDEFINED;
  if (ours) {
    JSValue proto = prototypeFor(ctx, global, hook);
    if (JS_IsObject(proto)) {
      target = JS_GetPropertyStr(ctx, proto, hook.methodName);
    }
    JS_FreeValue(ctx, proto);
  }
  JS_FreeValue(ctx, global);

  if (!JS_IsFunction(ctx, target)) {
    /* No layer, or it did not install this method: the engine's own behaviour,
       which is what the program would have had without this module. */
    JS_FreeValue(ctx, target);
    target = JS_DupValue(ctx, funcData[0]);
  }
  if (!JS_IsFunction(ctx, target)) {
    JS_FreeValue(ctx, target);
    return JS_ThrowTypeError(
        ctx, "%s.prototype.%s is not callable", hook.constructorName,
        hook.methodName);
  }
  JSValue result = JS_Call(ctx, target, thisVal, argc, argv);
  JS_FreeValue(ctx, target);
  return result;
}

void installLocaleHooks(JSContext *ctx) {
  JSValue global = JS_GetGlobalObject(ctx);
  for (int i = 0;
       i < static_cast<int>(sizeof(kLocaleHooks) / sizeof(kLocaleHooks[0]));
       i++) {
    const LocaleHook &hook = kLocaleHooks[i];
    JSValue proto = prototypeFor(ctx, global, hook);
    if (!JS_IsObject(proto)) {
      JS_FreeValue(ctx, proto);
      continue;
    }
    JSValue original = JS_GetPropertyStr(ctx, proto, hook.methodName);
    JSValueConst data[1] = {original};
    /*
     * NewCFunctionData2, for the name. A function created by
     * JS_NewCFunctionData has an empty `name`, and test262 checks the name
     * descriptor of every one of these methods
     * (BigInt/prototype/toLocaleString/name.js and friends). The trampoline is
     * observable through exactly that one property until it is replaced.
     */
    JSValue fn = JS_NewCFunctionData2(
        ctx, localeTrampoline, hook.methodName, hook.length, i, 1, data);
    JS_FreeValue(ctx, original);
    if (!JS_IsException(fn)) {
      /* The attributes ECMAScript gives these methods: writable, not
         enumerable, configurable. js/intl.js redefines them with exactly the
         same attributes, so the replacement is invisible to a descriptor check. */
      JS_DefinePropertyValueStr(
          ctx, proto, hook.methodName, fn,
          JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE);
    }
    JS_FreeValue(ctx, proto);
  }
  JS_FreeValue(ctx, global);
}

void installInto(JSContext *ctx) {
  if (ctx == nullptr) return;

  JSRuntime *rt = JS_GetRuntime(ctx);
  DtfHandle::registerIn(rt, "Intl.DateTimeFormat.Handle");
  NumHandle::registerIn(rt, "Intl.NumberFormat.Handle");
  ColHandle::registerIn(rt, "Intl.Collator.Handle");
  RtfHandle::registerIn(rt, "Intl.RelativeTimeFormat.Handle");
  LfHandle::registerIn(rt, "Intl.ListFormat.Handle");

  JSValue global = JS_GetGlobalObject(ctx);
  JSAtom atom = JS_NewAtom(ctx, "Intl");
  JSValue getter =
      JS_NewCFunction2(ctx, intlGetter, "get Intl", 0, JS_CFUNC_generic, 0);
  JSValue setter =
      JS_NewCFunction2(ctx, intlSetter, "set Intl", 1, JS_CFUNC_generic, 0);
  /* JS_PROP_CONFIGURABLE is load-bearing: without it the accessor cannot be
     replaced by the data property and the whole mechanism silently degrades
     into a getter call on every access. */
  JS_DefinePropertyGetSet(
      ctx, global, atom, getter, setter, JS_PROP_CONFIGURABLE);
  JS_FreeAtom(ctx, atom);
  JS_FreeValue(ctx, global);
  installLocaleHooks(ctx);
  RNQJS_INTL_COUNT(accessorInstalls);
}

#if defined(RNQJS_INTL_COUNTERS) && RNQJS_INTL_COUNTERS
void dumpCounters(std::FILE *out) {
  fprintf(
      out,
      "intl.accessorInstalls %lu\n"
      "intl.materializations %lu\n"
      "intl.blobLoads %lu\n"
      "intl.sourceLoads %lu\n"
      "intl.setterOverrides %lu\n",
      g_counters.accessorInstalls, g_counters.materializations,
      g_counters.blobLoads, g_counters.sourceLoads, g_counters.setterOverrides);
}
#endif

}  // namespace rnqjs::intl

extern "C" void rnqjs_intl_install(JSContext *ctx) {
  rnqjs::intl::installInto(ctx);
}

extern "C" void rnqjs_intl_dump_counters(void) {
#if defined(RNQJS_INTL_COUNTERS) && RNQJS_INTL_COUNTERS
  rnqjs::intl::dumpCounters(stdout);
#endif
}
